import type { Locale } from './i18n'

export type CheckoutCopy = {
  cart: string
  close: string
  empty: string
  remove: string
  total: string
  shipping: string
  seven: string
  home: string
  sevenTip: string
  homeTip: string
  mapCard: string
  mapCod: string
  mapRule: string
  mapNotReady: string
  selectedCvs: string
  codPick: string
  cardPick: string
  noLocalPickup: string
  namePh: string
  phonePh: string
  emailPh: string
  addrPh: string
  mapPh: string
  cvsPh: string
  payCard: string
  payCod: string
  processing: string
  tipSeven: string
  tipCardOnly: string
  errCodOnly: string
  errNoCod: string
  errName: string
  errPhone: string
  errAddr: string
  addToCart: string
  adding: string
  allCategory: string
  catalogTitle: string
  catalogCount: string
  paidPrefix: string
  paidCard: string
  paidCod: string
  paidThanks: string
  paidShipment: string
  addFail: string
  suspended: string
  checkoutFail: string
  loadingStore: string
  storeNotFound: string
  storeNotFoundTip: string
  openStoreCta: string
  noProducts: string
  homeNav: string
  pageNotFound: string
  pageNotFoundTip: string
  backHome: string
  productFallback: string
  trialEnded: string
  productsNav: string
  aboutNav: string
  errCancelled: string
  errCvsRequired: string
  errMapRequired: string
  errCollectionMismatch: string
  errAmountLimit: string
  errStripeUnavailable: string
  errStock: string
  storeFallback: string
  browseProducts: string
  slideN: string
  editingPrefix: string
  contactNav: string
  shippingPage: string
  returnsPage: string
  aboutBody: string
  contactBody: string
  shippingBody: string
  returnsBody: string
}

const zhTW: CheckoutCopy = {
  cart: '購物車',
  close: '關閉',
  empty: '購物車是空的',
  remove: '移除',
  total: '合計',
  shipping: '配送方式',
  seven: '7-11 取貨',
  home: '宅配／其他',
  sevenTip: '7-11：用地圖選門市後可刷卡或貨到付款；店家會取得 ibon 寄件代碼。',
  homeTip: '宅配／其他：僅接受信用卡付款。',
  mapCard: '刷卡取貨：開啟地圖選門市',
  mapCod: '貨到付款：開啟地圖選門市',
  mapRule: '綠界規定：選店時的「是否代收」必須跟付款方式一致，請依上方按鈕分開選。',
  mapNotReady: '此商店尚未開通 7-11 電子地圖。店家請至後台「收款／物流」依說明完成串接；開通前可暫時手填門市，但不會有正式寄件代碼。',
  selectedCvs: '已選門市',
  codPick: '貨到付款選店',
  cardPick: '刷卡取貨選店',
  noLocalPickup: '僅宅配＋信用卡付款。',
  namePh: '收貨人全名 *',
  phonePh: '手機 *',
  emailPh: 'Email（選填）',
  addrPh: '收件地址 *',
  mapPh: '請先用地圖選門市（選完會自動填入）',
  cvsPh: '7-11 門市名稱／店號 *',
  payCard: '信用卡付款',
  payCod: '貨到付款下單',
  processing: '處理中...',
  tipSeven: '7-11 取貨可用刷卡或貨到付款；刷卡時收貨人請留全名。',
  tipCardOnly: '此配送方式僅能刷信用卡付款。',
  errCodOnly: '貨到付款僅限 7-11 取貨',
  errNoCod: '此商店不支援貨到付款',
  errName: '請填寫收貨人全名',
  errPhone: '請填寫手機號碼',
  errAddr: '請填寫收件地址',
  addToCart: '加入購物車',
  adding: '加入中...',
  allCategory: '全部',
  catalogTitle: '全部商品',
  catalogCount: '共 {n} 件商品',
  paidPrefix: '訂單',
  paidCard: '（信用卡付款）',
  paidCod: '（貨到付款）',
  paidThanks: '已成立。感謝購買！',
  paidShipment: '店家寄件代碼：{code}',
  addFail: '加入購物車失敗，請稍後再試',
  suspended: '此商店試用已結束，暫時無法下單。店家開通方案後即可恢復購買。',
  checkoutFail: '結帳失敗，請稍後再試',
  loadingStore: '載入店舖中...',
  storeNotFound: '找不到這間店',
  storeNotFoundTip: '網址尚未開通，或品牌名稱有誤。',
  openStoreCta: '免費開一間自己的店',
  noProducts: '尚未上架商品',
  homeNav: '首頁',
  pageNotFound: '找不到此頁面',
  pageNotFoundTip: '此頁尚未發佈或不存在。',
  backHome: '回首頁',
  productFallback: '商品',
  trialEnded: '此商店試用已結束，暫時無法購買',
  productsNav: '全部商品',
  aboutNav: '關於我們',
  errCancelled: '已取消付款，可重新結帳。',
  errCvsRequired: '請先選擇 7-11 門市',
  errMapRequired: '請先用電子地圖選擇 7-11 門市',
  errCollectionMismatch: '選店的代收設定與付款方式不一致，請重選門市',
  errAmountLimit: '7-11 取貨單筆上限為 NT$ 20,000',
  errStripeUnavailable: '信用卡付款暫時無法使用，請稍後再試或改選貨到付款',
  errStock: '庫存不足',
  storeFallback: '我的商店',
  browseProducts: '瀏覽商品',
  slideN: '第 {n} 張',
  editingPrefix: '編輯中 ·',
  contactNav: '聯絡我們',
  shippingPage: '配送政策',
  returnsPage: '退換貨政策',
  aboutBody: '{name} 用心挑選每一件商品，希望帶給顧客更好的生活體驗。\n\n我們相信好產品值得被好好介紹——歡迎在這裡認識我們的品牌故事與理念。',
  contactBody: '如需協助，請透過訂單備註留下聯絡方式，或於結帳時填寫正確的 Email／電話，我們會盡快回覆。\n\n店名：{name}',
  shippingBody: '台灣出貨商店可選 7-11 超商取貨（含貨到付款）或宅配。非台灣出貨商店目前僅支援宅配與信用卡付款。運費與到貨時間以店家說明為準。',
  returnsBody: '若商品有瑕疵或與描述不符，請於收貨後盡快與我們聯繫。未拆封／未使用之商品，依個案協助退換。',
}

const zhCN: CheckoutCopy = {
  cart: '购物车',
  close: '关闭',
  empty: '购物车是空的',
  remove: '移除',
  total: '合计',
  shipping: '配送方式',
  seven: '7-11 取货',
  home: '宅配／其他',
  sevenTip: '7-11：用地图选门市后可刷卡或货到付款；店家会取得寄件代码。',
  homeTip: '宅配／其他：仅接受信用卡付款。',
  mapCard: '刷卡取货：开启地图选门市',
  mapCod: '货到付款：开启地图选门市',
  mapRule: '选店时的「是否代收」必须跟付款方式一致，请依上方按钮分开选。',
  mapNotReady: '此商店尚未开通 7-11 电子地图。店家可至后台「收款／物流」完成串接；开通前可暂时手填门市。',
  selectedCvs: '已选门市',
  codPick: '货到付款选店',
  cardPick: '刷卡取货选店',
  noLocalPickup: '仅宅配＋信用卡付款。',
  namePh: '收货人全名 *',
  phonePh: '手机 *',
  emailPh: 'Email（选填）',
  addrPh: '收件地址 *',
  mapPh: '请先用地图选门市（选完会自动填入）',
  cvsPh: '7-11 门市名称／店号 *',
  payCard: '信用卡付款',
  payCod: '货到付款下单',
  processing: '处理中...',
  tipSeven: '7-11 取货可用刷卡或货到付款；刷卡时收货人请留全名。',
  tipCardOnly: '此配送方式仅能刷信用卡付款。',
  errCodOnly: '货到付款仅限 7-11 取货',
  errNoCod: '此商店不支持货到付款',
  errName: '请填写收货人全名',
  errPhone: '请填写手机号码',
  errAddr: '请填写收件地址',
  addToCart: '加入购物车',
  adding: '加入中...',
  allCategory: '全部',
  catalogTitle: '全部商品',
  catalogCount: '共 {n} 件商品',
  paidPrefix: '订单',
  paidCard: '（信用卡付款）',
  paidCod: '（货到付款）',
  paidThanks: '已成立。感谢购买！',
  paidShipment: '店家寄件代码：{code}',
  addFail: '加入购物车失败，请稍后再试',
  suspended: '此商店试用已结束，暂时无法下单。店家开通方案后即可恢复购买。',
  checkoutFail: '结账失败，请稍后再试',
  loadingStore: '加载店铺中...',
  storeNotFound: '找不到这家店',
  storeNotFoundTip: '网址尚未开通，或品牌名称有误。',
  openStoreCta: '免费开一间自己的店',
  noProducts: '尚未上架商品',
  homeNav: '首页',
  pageNotFound: '找不到此页面',
  pageNotFoundTip: '此页尚未发布或不存在。',
  backHome: '回首页',
  productFallback: '商品',
  trialEnded: '此商店试用已结束，暂时无法购买',
  productsNav: '全部商品',
  aboutNav: '关于我们',
  errCancelled: '已取消付款，可重新结账。',
  errCvsRequired: '请先选择 7-11 门市',
  errMapRequired: '请先用地图选择 7-11 门市',
  errCollectionMismatch: '选店的代收设置与付款方式不一致，请重选门市',
  errAmountLimit: '7-11 取货单笔上限为 NT$ 20,000',
  errStripeUnavailable: '信用卡付款暂时无法使用，请稍后再试或改选货到付款',
  errStock: '库存不足',
  storeFallback: '我的商店',
  browseProducts: '浏览商品',
  slideN: '第 {n} 张',
  editingPrefix: '编辑中 ·',
  contactNav: '联系我们',
  shippingPage: '配送政策',
  returnsPage: '退换货政策',
  aboutBody: '{name} 用心挑选每一件商品，希望带给顾客更好的生活体验。\n\n我们相信好产品值得被好好介绍——欢迎在这里认识我们的品牌故事与理念。',
  contactBody: '如需协助，请通过订单备注留下联系方式，或于结账时填写正确的 Email／电话，我们会尽快回复。\n\n店名：{name}',
  shippingBody: '台湾出货商店可选 7-11 超商取货（含货到付款）或宅配。非台湾出货商店目前仅支持宅配与信用卡付款。运费与到货时间以店家说明为准。',
  returnsBody: '若商品有瑕疵或与描述不符，请于收货后尽快与我们联系。未拆封／未使用的商品，依个案协助退换。',
}

const en: CheckoutCopy = {
  cart: 'Cart',
  close: 'Close',
  empty: 'Your cart is empty',
  remove: 'Remove',
  total: 'Total',
  shipping: 'Shipping',
  seven: '7-11 pickup',
  home: 'Home delivery',
  sevenTip: '7-11: pick a store on the map, then pay by card or cash on delivery.',
  homeTip: 'Home delivery: card payment only.',
  mapCard: 'Card pickup: open map',
  mapCod: 'Cash on delivery: open map',
  mapRule: 'Collection setting on the map must match your payment method.',
  mapNotReady: 'This store has not enabled 7-11 map pickup yet. Merchants can set it up under Payments / logistics.',
  selectedCvs: 'Selected store',
  codPick: 'COD store pick',
  cardPick: 'Card store pick',
  noLocalPickup: 'Home delivery + card payment only.',
  namePh: 'Recipient full name *',
  phonePh: 'Phone *',
  emailPh: 'Email (optional)',
  addrPh: 'Delivery address *',
  mapPh: 'Pick a store on the map first',
  cvsPh: '7-11 store name / ID *',
  payCard: 'Pay by card',
  payCod: 'Cash on delivery',
  processing: 'Processing...',
  tipSeven: '7-11 supports card or cash on delivery. Use full name for card orders.',
  tipCardOnly: 'Card payment only for this shipping method.',
  errCodOnly: 'Cash on delivery is only for 7-11 pickup',
  errNoCod: 'This store does not support cash on delivery',
  errName: 'Please enter the recipient’s full name',
  errPhone: 'Please enter a phone number',
  errAddr: 'Please enter a delivery address',
  addToCart: 'Add to cart',
  adding: 'Adding...',
  allCategory: 'All',
  catalogTitle: 'All products',
  catalogCount: '{n} products',
  paidPrefix: 'Order',
  paidCard: '(card payment)',
  paidCod: '(cash on delivery)',
  paidThanks: 'is confirmed. Thank you!',
  paidShipment: 'Merchant shipment code: {code}',
  addFail: 'Could not add to cart. Please try again.',
  suspended: 'This store’s trial has ended. Orders are paused until a plan is activated.',
  checkoutFail: 'Checkout failed. Please try again.',
  loadingStore: 'Loading store...',
  storeNotFound: 'Store not found',
  storeNotFoundTip: 'This URL is not active, or the brand name is wrong.',
  openStoreCta: 'Open your own store for free',
  noProducts: 'No products yet',
  homeNav: 'Home',
  pageNotFound: 'Page not found',
  pageNotFoundTip: 'This page is unpublished or does not exist.',
  backHome: 'Back to home',
  productFallback: 'Product',
  trialEnded: 'This store’s trial has ended. Purchases are temporarily unavailable.',
  productsNav: 'All products',
  aboutNav: 'About',
  errCancelled: 'Payment cancelled. You can try checkout again.',
  errCvsRequired: 'Please select a 7-11 store first',
  errMapRequired: 'Please pick a 7-11 store on the map',
  errCollectionMismatch: 'Store pickup collection setting must match payment method',
  errAmountLimit: '7-11 orders are limited to NT$ 20,000',
  errStripeUnavailable: 'Card payment is temporarily unavailable. Try again or use cash on delivery.',
  errStock: 'Not enough stock',
  storeFallback: 'My store',
  browseProducts: 'Shop now',
  slideN: 'Slide {n}',
  editingPrefix: 'Editing ·',
  contactNav: 'Contact us',
  shippingPage: 'Shipping policy',
  returnsPage: 'Returns policy',
  aboutBody: '{name} carefully selects every product so customers get a better everyday experience.\n\nGood products deserve a clear story — this page is where you meet the brand.',
  contactBody: 'Need help? Leave a note on your order, or use a valid email / phone at checkout. We will reply as soon as we can.\n\nStore: {name}',
  shippingBody: 'Taiwan-shipping stores can offer 7-11 pickup (including cash on delivery) or home delivery. Other stores currently support home delivery and card payment. Fees and timing follow the merchant’s instructions.',
  returnsBody: 'If an item is defective or not as described, contact us soon after delivery. Unopened / unused items can be reviewed case by case.',
}

const ko: CheckoutCopy = {
  cart: '장바구니',
  close: '닫기',
  empty: '장바구니가 비어 있습니다',
  remove: '삭제',
  total: '합계',
  shipping: '배송 방법',
  seven: '7-11 픽업',
  home: '택배／기타',
  sevenTip: '7-11: 지도에서 매장을 선택한 뒤 카드 또는 착불로 결제할 수 있습니다.',
  homeTip: '택배／기타: 카드 결제만 가능합니다.',
  mapCard: '카드 픽업: 지도 열기',
  mapCod: '착불: 지도 열기',
  mapRule: '지도의 대금수령 설정이 결제 방식과 일치해야 합니다.',
  mapNotReady: '이 스토어는 아직 7-11 지도 픽업이 연결되지 않았습니다.',
  selectedCvs: '선택한 매장',
  codPick: '착불 매장 선택',
  cardPick: '카드 매장 선택',
  noLocalPickup: '택배 + 카드 결제만 가능합니다.',
  namePh: '수령인 성명 *',
  phonePh: '휴대폰 *',
  emailPh: '이메일（선택）',
  addrPh: '배송 주소 *',
  mapPh: '먼저 지도에서 매장을 선택하세요',
  cvsPh: '7-11 매장명／번호 *',
  payCard: '카드로 결제',
  payCod: '착불로 주문',
  processing: '처리 중...',
  tipSeven: '7-11은 카드 또는 착불을 사용할 수 있습니다. 카드 결제 시 성명을 입력하세요.',
  tipCardOnly: '이 배송 방법은 카드 결제만 가능합니다.',
  errCodOnly: '착불은 7-11 픽업만 가능합니다',
  errNoCod: '이 스토어는 착불을 지원하지 않습니다',
  errName: '수령인 성명을 입력해 주세요',
  errPhone: '휴대폰 번호를 입력해 주세요',
  errAddr: '배송 주소를 입력해 주세요',
  addToCart: '장바구니 담기',
  adding: '담는 중...',
  allCategory: '전체',
  catalogTitle: '전체 상품',
  catalogCount: '상품 {n}개',
  paidPrefix: '주문',
  paidCard: '(카드 결제)',
  paidCod: '(착불)',
  paidThanks: '이 확정되었습니다. 감사합니다!',
  paidShipment: '판매자 발송 코드: {code}',
  addFail: '장바구니에 담지 못했습니다. 다시 시도해 주세요.',
  suspended: '이 스토어 체험이 종료되어 주문이 일시 중지되었습니다. 요금제 활성화 후 다시 구매할 수 있습니다.',
  checkoutFail: '결제에 실패했습니다. 다시 시도해 주세요.',
  loadingStore: '스토어 불러오는 중...',
  storeNotFound: '스토어를 찾을 수 없습니다',
  storeNotFoundTip: '이 주소가 개설되지 않았거나 브랜드명이 올바르지 않습니다.',
  openStoreCta: '무료로 내 스토어 만들기',
  noProducts: '등록된 상품이 없습니다',
  homeNav: '홈',
  pageNotFound: '페이지를 찾을 수 없습니다',
  pageNotFoundTip: '이 페이지는 게시되지 않았거나 존재하지 않습니다.',
  backHome: '홈으로',
  productFallback: '상품',
  trialEnded: '이 스토어 체험이 종료되어 일시적으로 구매할 수 없습니다.',
  productsNav: '전체 상품',
  aboutNav: '소개',
  errCancelled: '결제가 취소되었습니다. 다시 결제할 수 있습니다.',
  errCvsRequired: '먼저 7-11 매장을 선택해 주세요',
  errMapRequired: '지도에서 7-11 매장을 선택해 주세요',
  errCollectionMismatch: '매장 수금 설정이 결제 방식과 일치하지 않습니다. 다시 선택해 주세요',
  errAmountLimit: '7-11 주문은 NT$ 20,000 한도입니다',
  errStripeUnavailable: '카드 결제를 잠시 사용할 수 없습니다. 나중에 다시 시도하거나 착불을 이용하세요.',
  errStock: '재고가 부족합니다',
  storeFallback: '내 스토어',
  browseProducts: '상품 보기',
  slideN: '{n}번째 슬라이드',
  editingPrefix: '편집 중 ·',
  contactNav: '문의',
  shippingPage: '배송 정책',
  returnsPage: '교환·반품 정책',
  aboutBody: '{name}는 더 나은 일상을 위해 상품을 신중히 고릅니다.\n\n좋은 제품은 제대로 소개되어야 합니다. 여기에서 브랜드 이야기를 만나 보세요.',
  contactBody: '도움이 필요하면 주문 메모를 남기거나, 결제 시 올바른 이메일/전화를 적어 주세요. 최대한 빠르게 답변드립니다.\n\n스토어: {name}',
  shippingBody: '대만 출고 스토어는 7-11 픽업(착불 포함) 또는 택배 배송을 제공할 수 있습니다. 그 외 스토어는 현재 택배와 카드 결제를 지원합니다. 배송비와 기간은 판매자 안내를 따릅니다.',
  returnsBody: '상품에 하자가 있거나 설명과 다르면 수령 후 바로 연락해 주세요. 미개봉/미사용 상품은 건별로 도와드립니다.',
}

const ja: CheckoutCopy = {
  cart: 'カート',
  close: '閉じる',
  empty: 'カートは空です',
  remove: '削除',
  total: '合計',
  shipping: '配送方法',
  seven: '7-11 受取',
  home: '宅配／その他',
  sevenTip: '7-11：地図で店舗を選んだあと、カードまたは代金引換で支払えます。',
  homeTip: '宅配／その他：カード決済のみ。',
  mapCard: 'カード受取：地図を開く',
  mapCod: '代金引換：地図を開く',
  mapRule: '地図の代収設定は支払い方法と一致させてください。',
  mapNotReady: 'この店舗はまだ 7-11 地図受取が未設定です。',
  selectedCvs: '選択した店舗',
  codPick: '代金引換の店舗選択',
  cardPick: 'カード受取の店舗選択',
  noLocalPickup: '宅配＋カード決済のみです。',
  namePh: '受取人氏名 *',
  phonePh: '携帯番号 *',
  emailPh: 'メール（任意）',
  addrPh: '配送先住所 *',
  mapPh: '先に地図で店舗を選択してください',
  cvsPh: '7-11 店名／店番号 *',
  payCard: 'カードで支払う',
  payCod: '代金引換で注文',
  processing: '処理中...',
  tipSeven: '7-11 はカードまたは代金引換に対応。カード時は氏名を入力してください。',
  tipCardOnly: 'この配送方法はカード決済のみです。',
  errCodOnly: '代金引換は 7-11 受取のみです',
  errNoCod: 'この店舗は代金引換に対応していません',
  errName: '受取人氏名を入力してください',
  errPhone: '携帯番号を入力してください',
  errAddr: '配送先住所を入力してください',
  addToCart: 'カートに入れる',
  adding: '追加中...',
  allCategory: 'すべて',
  catalogTitle: 'すべての商品',
  catalogCount: '全 {n} 点',
  paidPrefix: '注文',
  paidCard: '（カード決済）',
  paidCod: '（代金引換）',
  paidThanks: 'が確定しました。ありがとうございます！',
  paidShipment: '出品者の出荷コード: {code}',
  addFail: 'カートに追加できませんでした。再度お試しください。',
  suspended: 'この店舗のトライアルは終了し、注文を一時停止しています。プラン開通後に再開できます。',
  checkoutFail: 'チェックアウトに失敗しました。再度お試しください。',
  loadingStore: '店舗を読み込み中...',
  storeNotFound: '店舗が見つかりません',
  storeNotFoundTip: 'このURLは未開通か、ブランド名が正しくありません。',
  openStoreCta: '無料で自分の店を開く',
  noProducts: '商品はまだありません',
  homeNav: 'ホーム',
  pageNotFound: 'ページが見つかりません',
  pageNotFoundTip: 'このページは未公開か、存在しません。',
  backHome: 'ホームへ戻る',
  productFallback: '商品',
  trialEnded: 'この店舗のトライアルは終了し、一時的に購入できません。',
  productsNav: 'すべての商品',
  aboutNav: '私たちについて',
  errCancelled: '支払いがキャンセルされました。再度お試しください。',
  errCvsRequired: '先に 7-11 店舗を選択してください',
  errMapRequired: '地図で 7-11 店舗を選択してください',
  errCollectionMismatch: '店舗の代収設定が支払い方法と一致しません。選び直してください',
  errAmountLimit: '7-11 は 1 件 NT$ 20,000 までです',
  errStripeUnavailable: 'カード決済を一時利用できません。後でもう一度お試しいただくか代金引換をご利用ください。',
  errStock: '在庫が不足しています',
  storeFallback: 'マイストア',
  browseProducts: '商品を見る',
  slideN: '{n}枚目',
  editingPrefix: '編集中 ·',
  contactNav: 'お問い合わせ',
  shippingPage: '配送ポリシー',
  returnsPage: '返品・交換ポリシー',
  aboutBody: '{name} は、より良い日常のために商品を丁寧に選んでいます。\n\n良い商品はきちんと紹介されるべきです。ここではブランドの物語をご覧ください。',
  contactBody: 'ご不明点は注文メモを残すか、お会計時に正しいメール／電話をご記入ください。できるだけ早くご返信します。\n\nストア：{name}',
  shippingBody: '台湾発送のストアは 7-11 受け取り（代金引換を含む）または宅配を選べます。その他のストアは現在、宅配とカード決済です。送料とお届け目安は販売者の案内に従ってください。',
  returnsBody: '不良や記載違いがある場合は、到着後できるだけ早くご連絡ください。未開封／未使用の商品は個別に対応します。',
}

const vi: CheckoutCopy = {
  cart: 'Giỏ hàng',
  close: 'Đóng',
  empty: 'Giỏ hàng trống',
  remove: 'Xóa',
  total: 'Tổng',
  shipping: 'Phương thức giao hàng',
  seven: 'Nhận tại 7-11',
  home: 'Giao tận nhà／Khác',
  sevenTip: '7-11: chọn cửa hàng trên bản đồ, rồi thanh toán thẻ hoặc COD.',
  homeTip: 'Giao tận nhà／Khác: chỉ thanh toán thẻ.',
  mapCard: 'Nhận bằng thẻ: mở bản đồ',
  mapCod: 'COD: mở bản đồ',
  mapRule: 'Cài đặt thu hộ trên bản đồ phải khớp phương thức thanh toán.',
  mapNotReady: 'Cửa hàng chưa bật bản đồ nhận hàng 7-11.',
  selectedCvs: 'Cửa hàng đã chọn',
  codPick: 'Chọn cửa hàng COD',
  cardPick: 'Chọn cửa hàng thẻ',
  noLocalPickup: 'Chỉ giao tận nhà + thanh toán thẻ.',
  namePh: 'Họ tên người nhận *',
  phonePh: 'Điện thoại *',
  emailPh: 'Email (tuỳ chọn)',
  addrPh: 'Địa chỉ giao hàng *',
  mapPh: 'Hãy chọn cửa hàng trên bản đồ trước',
  cvsPh: 'Tên／mã cửa hàng 7-11 *',
  payCard: 'Thanh toán thẻ',
  payCod: 'Đặt hàng COD',
  processing: 'Đang xử lý...',
  tipSeven: '7-11 hỗ trợ thẻ hoặc COD. Khi trả thẻ hãy ghi họ tên đầy đủ.',
  tipCardOnly: 'Phương thức giao này chỉ nhận thanh toán thẻ.',
  errCodOnly: 'COD chỉ áp dụng cho nhận tại 7-11',
  errNoCod: 'Cửa hàng không hỗ trợ COD',
  errName: 'Vui lòng nhập họ tên người nhận',
  errPhone: 'Vui lòng nhập số điện thoại',
  errAddr: 'Vui lòng nhập địa chỉ giao hàng',
  addToCart: 'Thêm vào giỏ',
  adding: 'Đang thêm...',
  allCategory: 'Tất cả',
  catalogTitle: 'Tất cả sản phẩm',
  catalogCount: '{n} sản phẩm',
  paidPrefix: 'Đơn',
  paidCard: '(thanh toán thẻ)',
  paidCod: '(COD)',
  paidThanks: 'đã xác nhận. Cảm ơn bạn!',
  paidShipment: 'Mã gửi hàng: {code}',
  addFail: 'Không thêm được vào giỏ. Vui lòng thử lại.',
  suspended: 'Gói dùng thử của cửa hàng đã hết. Đơn hàng tạm dừng đến khi kích hoạt gói.',
  checkoutFail: 'Thanh toán thất bại. Vui lòng thử lại.',
  loadingStore: 'Đang tải cửa hàng...',
  storeNotFound: 'Không tìm thấy cửa hàng',
  storeNotFoundTip: 'URL chưa mở hoặc tên thương hiệu không đúng.',
  openStoreCta: 'Mở cửa hàng miễn phí',
  noProducts: 'Chưa có sản phẩm',
  homeNav: 'Trang chủ',
  pageNotFound: 'Không tìm thấy trang',
  pageNotFoundTip: 'Trang chưa xuất bản hoặc không tồn tại.',
  backHome: 'Về trang chủ',
  productFallback: 'Sản phẩm',
  trialEnded: 'Gói dùng thử đã hết. Tạm thời không thể mua.',
  productsNav: 'Tất cả sản phẩm',
  aboutNav: 'Giới thiệu',
  errCancelled: 'Đã hủy thanh toán. Bạn có thể thanh toán lại.',
  errCvsRequired: 'Hãy chọn cửa hàng 7-11 trước',
  errMapRequired: 'Hãy chọn cửa hàng 7-11 trên bản đồ',
  errCollectionMismatch: 'Cài đặt thu hộ không khớp phương thức thanh toán',
  errAmountLimit: 'Đơn 7-11 tối đa NT$ 20,000',
  errStripeUnavailable: 'Thanh toán thẻ tạm thời không khả dụng. Thử lại hoặc dùng COD.',
  errStock: 'Không đủ tồn kho',
  storeFallback: 'Cửa hàng của tôi',
  browseProducts: 'Xem sản phẩm',
  slideN: 'Ảnh {n}',
  editingPrefix: 'Đang sửa ·',
  contactNav: 'Liên hệ',
  shippingPage: 'Chính sách giao hàng',
  returnsPage: 'Đổi trả',
  aboutBody: '{name} chọn từng sản phẩm để khách có trải nghiệm tốt hơn.\n\nSản phẩm tốt đáng được giới thiệu tử tế — trang này là câu chuyện thương hiệu.',
  contactBody: 'Cần hỗ trợ? Để ghi chú trên đơn, hoặc điền email / điện thoại đúng khi thanh toán. Chúng tôi sẽ phản hồi sớm.\n\nCửa hàng: {name}',
  shippingBody: 'Cửa hàng giao từ Đài Loan có thể dùng nhận hàng 7-11 (kể cả COD) hoặc giao tận nhà. Cửa hàng khác hiện hỗ trợ giao nhà và thanh toán thẻ. Phí và thời gian theo hướng dẫn của chủ shop.',
  returnsBody: 'Nếu hàng lỗi hoặc khác mô tả, hãy liên hệ sớm sau khi nhận. Hàng chưa mở / chưa dùng sẽ được xem xét từng trường hợp.',
}

const es: CheckoutCopy = {
  cart: 'Carrito',
  close: 'Cerrar',
  empty: 'Tu carrito está vacío',
  remove: 'Quitar',
  total: 'Total',
  shipping: 'Envío',
  seven: 'Recogida 7-11',
  home: 'Entrega a domicilio',
  sevenTip: '7-11: elige tienda en el mapa y paga con tarjeta o contra reembolso.',
  homeTip: 'Entrega a domicilio: solo pago con tarjeta.',
  mapCard: 'Recogida con tarjeta: abrir mapa',
  mapCod: 'Contra reembolso: abrir mapa',
  mapRule: 'La opción de cobro del mapa debe coincidir con el pago.',
  mapNotReady: 'Esta tienda aún no tiene el mapa 7-11 activado.',
  selectedCvs: 'Tienda seleccionada',
  codPick: 'Selección COD',
  cardPick: 'Selección con tarjeta',
  noLocalPickup: 'Solo entrega a domicilio + pago con tarjeta.',
  namePh: 'Nombre completo del destinatario *',
  phonePh: 'Teléfono *',
  emailPh: 'Email (opcional)',
  addrPh: 'Dirección de entrega *',
  mapPh: 'Elige primero una tienda en el mapa',
  cvsPh: 'Nombre／ID de tienda 7-11 *',
  payCard: 'Pagar con tarjeta',
  payCod: 'Pedir contra reembolso',
  processing: 'Procesando...',
  tipSeven: '7-11 admite tarjeta o contra reembolso. Usa el nombre completo con tarjeta.',
  tipCardOnly: 'Solo pago con tarjeta para este envío.',
  errCodOnly: 'El contra reembolso solo aplica a recogida 7-11',
  errNoCod: 'Esta tienda no admite contra reembolso',
  errName: 'Introduce el nombre completo del destinatario',
  errPhone: 'Introduce un teléfono',
  errAddr: 'Introduce una dirección de entrega',
  addToCart: 'Añadir al carrito',
  adding: 'Añadiendo...',
  allCategory: 'Todo',
  catalogTitle: 'Todos los productos',
  catalogCount: '{n} productos',
  paidPrefix: 'Pedido',
  paidCard: '(pago con tarjeta)',
  paidCod: '(contra reembolso)',
  paidThanks: 'confirmado. ¡Gracias!',
  paidShipment: 'Código de envío: {code}',
  addFail: 'No se pudo añadir al carrito. Inténtalo de nuevo.',
  suspended: 'La prueba de esta tienda terminó. Los pedidos están en pausa hasta activar un plan.',
  checkoutFail: 'El pago falló. Inténtalo de nuevo.',
  loadingStore: 'Cargando tienda...',
  storeNotFound: 'Tienda no encontrada',
  storeNotFoundTip: 'Esta URL no está activa o el nombre de marca es incorrecto.',
  openStoreCta: 'Abre tu propia tienda gratis',
  noProducts: 'Aún no hay productos',
  homeNav: 'Inicio',
  pageNotFound: 'Página no encontrada',
  pageNotFoundTip: 'Esta página no está publicada o no existe.',
  backHome: 'Volver al inicio',
  productFallback: 'Producto',
  trialEnded: 'La prueba terminó. Las compras están temporalmente no disponibles.',
  productsNav: 'Todos los productos',
  aboutNav: 'Sobre nosotros',
  errCancelled: 'Pago cancelado. Puedes intentar de nuevo.',
  errCvsRequired: 'Selecciona primero una tienda 7-11',
  errMapRequired: 'Elige una tienda 7-11 en el mapa',
  errCollectionMismatch: 'La opción de cobro debe coincidir con el pago',
  errAmountLimit: 'Pedidos 7-11 limitados a NT$ 20,000',
  errStripeUnavailable: 'El pago con tarjeta no está disponible. Inténtalo luego o usa contra reembolso.',
  errStock: 'Stock insuficiente',
  storeFallback: 'Mi tienda',
  browseProducts: 'Ver productos',
  slideN: 'Diapositiva {n}',
  editingPrefix: 'Editando ·',
  contactNav: 'Contacto',
  shippingPage: 'Política de envío',
  returnsPage: 'Devoluciones',
  aboutBody: '{name} elige cada producto para que la compra se sienta mejor.\n\nUn buen producto merece una historia clara; aquí conoces la marca.',
  contactBody: '¿Necesitas ayuda? Deja una nota en el pedido o un email / teléfono válido al pagar. Responderemos lo antes posible.\n\nTienda: {name}',
  shippingBody: 'Las tiendas que envían desde Taiwán pueden ofrecer recogida 7-11 (incluido contra reembolso) o envío a domicilio. Las demás ahora usan domicilio y pago con tarjeta. Gastos y plazos los indica el comercio.',
  returnsBody: 'Si el artículo es defectuoso o no coincide con la descripción, contáctanos pronto. Los productos sin abrir / sin usar se revisan caso por caso.',
}

const pt: CheckoutCopy = {
  cart: 'Carrinho',
  close: 'Fechar',
  empty: 'Seu carrinho está vazio',
  remove: 'Remover',
  total: 'Total',
  shipping: 'Envio',
  seven: 'Retirada 7-11',
  home: 'Entrega em domicílio',
  sevenTip: '7-11: escolha a loja no mapa e pague com cartão ou na entrega.',
  homeTip: 'Entrega em domicílio: apenas cartão.',
  mapCard: 'Retirada com cartão: abrir mapa',
  mapCod: 'Pagamento na entrega: abrir mapa',
  mapRule: 'A opção de cobrança no mapa deve combinar com o pagamento.',
  mapNotReady: 'Esta loja ainda não ativou o mapa 7-11.',
  selectedCvs: 'Loja selecionada',
  codPick: 'Seleção COD',
  cardPick: 'Seleção com cartão',
  noLocalPickup: 'Apenas entrega em domicílio + cartão.',
  namePh: 'Nome completo do destinatário *',
  phonePh: 'Telefone *',
  emailPh: 'E-mail (opcional)',
  addrPh: 'Endereço de entrega *',
  mapPh: 'Escolha primeiro uma loja no mapa',
  cvsPh: 'Nome／ID da loja 7-11 *',
  payCard: 'Pagar com cartão',
  payCod: 'Pedir com pagamento na entrega',
  processing: 'Processando...',
  tipSeven: '7-11 aceita cartão ou pagamento na entrega. Use o nome completo no cartão.',
  tipCardOnly: 'Apenas pagamento com cartão neste envio.',
  errCodOnly: 'Pagamento na entrega só vale para retirada 7-11',
  errNoCod: 'Esta loja não aceita pagamento na entrega',
  errName: 'Informe o nome completo do destinatário',
  errPhone: 'Informe um telefone',
  errAddr: 'Informe um endereço de entrega',
  addToCart: 'Adicionar ao carrinho',
  adding: 'Adicionando...',
  allCategory: 'Todos',
  catalogTitle: 'Todos os produtos',
  catalogCount: '{n} produtos',
  paidPrefix: 'Pedido',
  paidCard: '(pagamento com cartão)',
  paidCod: '(pagamento na entrega)',
  paidThanks: 'confirmado. Obrigado!',
  paidShipment: 'Código de envio: {code}',
  addFail: 'Não foi possível adicionar ao carrinho. Tente de novo.',
  suspended: 'O período de teste desta loja terminou. Pedidos pausados até ativar um plano.',
  checkoutFail: 'Checkout falhou. Tente de novo.',
  loadingStore: 'Carregando loja...',
  storeNotFound: 'Loja não encontrada',
  storeNotFoundTip: 'Este URL não está ativo ou o nome da marca está errado.',
  openStoreCta: 'Abra sua própria loja grátis',
  noProducts: 'Ainda sem produtos',
  homeNav: 'Início',
  pageNotFound: 'Página não encontrada',
  pageNotFoundTip: 'Esta página não foi publicada ou não existe.',
  backHome: 'Voltar ao início',
  productFallback: 'Produto',
  trialEnded: 'O período de teste terminou. Compras temporariamente indisponíveis.',
  productsNav: 'Todos os produtos',
  aboutNav: 'Sobre',
  errCancelled: 'Pagamento cancelado. Você pode tentar de novo.',
  errCvsRequired: 'Selecione primeiro uma loja 7-11',
  errMapRequired: 'Escolha uma loja 7-11 no mapa',
  errCollectionMismatch: 'A cobrança da loja deve combinar com o pagamento',
  errAmountLimit: 'Pedidos 7-11 limitados a NT$ 20,000',
  errStripeUnavailable: 'Pagamento com cartão indisponível. Tente depois ou use pagamento na entrega.',
  errStock: 'Estoque insuficiente',
  storeFallback: 'Minha loja',
  browseProducts: 'Ver produtos',
  slideN: 'Slide {n}',
  editingPrefix: 'Editando ·',
  contactNav: 'Fale conosco',
  shippingPage: 'Política de envio',
  returnsPage: 'Trocas e devoluções',
  aboutBody: '{name} escolhe cada produto para uma experiência melhor no dia a dia.\n\nUm bom produto merece uma história clara — conheça a marca aqui.',
  contactBody: 'Precisa de ajuda? Deixe um recado no pedido ou um e-mail / telefone válido no checkout. Responderemos o mais rápido possível.\n\nLoja: {name}',
  shippingBody: 'Lojas que enviam de Taiwan podem oferecer retirada 7-11 (incluindo pagamento na entrega) ou entrega em casa. As demais hoje usam entrega e cartão. Frete e prazo seguem o anunciado pelo lojista.',
  returnsBody: 'Se o item vier com defeito ou diferente da descrição, fale conosco logo após receber. Itens lacrados / não usados são analisados caso a caso.',
}

const de: CheckoutCopy = {
  cart: 'Warenkorb',
  close: 'Schließen',
  empty: 'Ihr Warenkorb ist leer',
  remove: 'Entfernen',
  total: 'Summe',
  shipping: 'Versand',
  seven: '7-11 Abholung',
  home: 'Lieferung nach Hause',
  sevenTip: '7-11: Filiale auf der Karte wählen, dann Karte oder Nachnahme.',
  homeTip: 'Lieferung nach Hause: nur Kartenzahlung.',
  mapCard: 'Kartenabholung: Karte öffnen',
  mapCod: 'Nachnahme: Karte öffnen',
  mapRule: 'Die Inkasso-Einstellung auf der Karte muss zur Zahlung passen.',
  mapNotReady: 'Dieser Shop hat die 7-11-Karte noch nicht aktiviert.',
  selectedCvs: 'Gewählte Filiale',
  codPick: 'Nachnahme-Filiale',
  cardPick: 'Karten-Filiale',
  noLocalPickup: 'Nur Lieferung nach Hause + Kartenzahlung.',
  namePh: 'Vollständiger Name des Empfängers *',
  phonePh: 'Telefon *',
  emailPh: 'E-Mail (optional)',
  addrPh: 'Lieferadresse *',
  mapPh: 'Bitte zuerst eine Filiale auf der Karte wählen',
  cvsPh: '7-11 Filialname／ID *',
  payCard: 'Mit Karte zahlen',
  payCod: 'Per Nachnahme bestellen',
  processing: 'Wird verarbeitet...',
  tipSeven: '7-11 unterstützt Karte oder Nachnahme. Bei Karte bitte vollständigen Namen angeben.',
  tipCardOnly: 'Für diese Versandart nur Kartenzahlung.',
  errCodOnly: 'Nachnahme nur bei 7-11 Abholung',
  errNoCod: 'Dieser Shop unterstützt keine Nachnahme',
  errName: 'Bitte den vollständigen Namen des Empfängers eingeben',
  errPhone: 'Bitte eine Telefonnummer eingeben',
  errAddr: 'Bitte eine Lieferadresse eingeben',
  addToCart: 'In den Warenkorb',
  adding: 'Wird hinzugefügt...',
  allCategory: 'Alle',
  catalogTitle: 'Alle Produkte',
  catalogCount: '{n} Produkte',
  paidPrefix: 'Bestellung',
  paidCard: '(Kartenzahlung)',
  paidCod: '(Nachnahme)',
  paidThanks: 'ist bestätigt. Vielen Dank!',
  paidShipment: 'Versandcode: {code}',
  addFail: 'Konnte nicht in den Warenkorb gelegt werden. Bitte erneut versuchen.',
  suspended: 'Die Testphase dieses Shops ist beendet. Bestellungen sind pausiert, bis ein Plan aktiviert wird.',
  checkoutFail: 'Checkout fehlgeschlagen. Bitte erneut versuchen.',
  loadingStore: 'Shop wird geladen...',
  storeNotFound: 'Shop nicht gefunden',
  storeNotFoundTip: 'Diese URL ist nicht aktiv oder der Markenname ist falsch.',
  openStoreCta: 'Eigenen Shop kostenlos eröffnen',
  noProducts: 'Noch keine Produkte',
  homeNav: 'Start',
  pageNotFound: 'Seite nicht gefunden',
  pageNotFoundTip: 'Diese Seite ist unveröffentlicht oder existiert nicht.',
  backHome: 'Zurück zur Startseite',
  productFallback: 'Produkt',
  trialEnded: 'Die Testphase ist beendet. Käufe sind vorübergehend nicht möglich.',
  productsNav: 'Alle Produkte',
  aboutNav: 'Über uns',
  errCancelled: 'Zahlung abgebrochen. Sie können es erneut versuchen.',
  errCvsRequired: 'Bitte zuerst eine 7-11 Filiale wählen',
  errMapRequired: 'Bitte eine 7-11 Filiale auf der Karte wählen',
  errCollectionMismatch: 'Inkasso-Einstellung muss zur Zahlung passen',
  errAmountLimit: '7-11 Bestellungen max. NT$ 20,000',
  errStripeUnavailable: 'Kartenzahlung vorübergehend nicht verfügbar. Später erneut oder Nachnahme.',
  errStock: 'Nicht genug Lagerbestand',
  storeFallback: 'Mein Shop',
  browseProducts: 'Produkte ansehen',
  slideN: 'Folie {n}',
  editingPrefix: 'Bearbeitung ·',
  contactNav: 'Kontakt',
  shippingPage: 'Versandrichtlinie',
  returnsPage: 'Rückgabe',
  aboutBody: '{name} wählt jedes Produkt sorgfältig aus, damit der Alltag besser wird.\n\nGute Produkte verdienen eine klare Geschichte — hier lernen Sie die Marke kennen.',
  contactBody: 'Hilfe nötig? Hinterlassen Sie eine Notiz zur Bestellung oder eine gültige E-Mail / Telefonnummer an der Kasse. Wir antworten so schnell wie möglich.\n\nShop: {name}',
  shippingBody: 'Shops mit Versand aus Taiwan können 7-11-Abholung (inkl. Nachnahme) oder Hauslieferung anbieten. Andere Shops nutzen derzeit Hauslieferung und Kartenzahlung. Kosten und Zeitangaben macht der Händler.',
  returnsBody: 'Bei Defekt oder Abweichung von der Beschreibung bitte bald nach Erhalt melden. Ungeöffnete / unbenutzte Artikel prüfen wir im Einzelfall.',
}

const fr: CheckoutCopy = {
  cart: 'Panier',
  close: 'Fermer',
  empty: 'Votre panier est vide',
  remove: 'Retirer',
  total: 'Total',
  shipping: 'Livraison',
  seven: 'Retrait 7-11',
  home: 'Livraison à domicile',
  sevenTip: '7-11 : choisissez un magasin sur la carte, puis payez par carte ou à la livraison.',
  homeTip: 'Livraison à domicile : paiement par carte uniquement.',
  mapCard: 'Retrait carte : ouvrir la carte',
  mapCod: 'Paiement à la livraison : ouvrir la carte',
  mapRule: 'Le paramètre d’encaissement sur la carte doit correspondre au paiement.',
  mapNotReady: 'Cette boutique n’a pas encore activé la carte 7-11.',
  selectedCvs: 'Magasin sélectionné',
  codPick: 'Choix magasin COD',
  cardPick: 'Choix magasin carte',
  noLocalPickup: 'Livraison à domicile + paiement par carte uniquement.',
  namePh: 'Nom complet du destinataire *',
  phonePh: 'Téléphone *',
  emailPh: 'E-mail (facultatif)',
  addrPh: 'Adresse de livraison *',
  mapPh: 'Choisissez d’abord un magasin sur la carte',
  cvsPh: 'Nom／ID magasin 7-11 *',
  payCard: 'Payer par carte',
  payCod: 'Commander en paiement à la livraison',
  processing: 'Traitement...',
  tipSeven: '7-11 accepte carte ou paiement à la livraison. Indiquez le nom complet pour la carte.',
  tipCardOnly: 'Paiement par carte uniquement pour cette livraison.',
  errCodOnly: 'Le paiement à la livraison est réservé au retrait 7-11',
  errNoCod: 'Cette boutique n’accepte pas le paiement à la livraison',
  errName: 'Veuillez saisir le nom complet du destinataire',
  errPhone: 'Veuillez saisir un numéro de téléphone',
  errAddr: 'Veuillez saisir une adresse de livraison',
  addToCart: 'Ajouter au panier',
  adding: 'Ajout...',
  allCategory: 'Tout',
  catalogTitle: 'Tous les produits',
  catalogCount: '{n} produits',
  paidPrefix: 'Commande',
  paidCard: '(paiement par carte)',
  paidCod: '(paiement à la livraison)',
  paidThanks: 'confirmée. Merci !',
  paidShipment: 'Code d’expédition : {code}',
  addFail: 'Impossible d’ajouter au panier. Réessayez.',
  suspended: 'L’essai de cette boutique est terminé. Les commandes sont en pause jusqu’à l’activation d’un forfait.',
  checkoutFail: 'Échec du paiement. Réessayez.',
  loadingStore: 'Chargement de la boutique...',
  storeNotFound: 'Boutique introuvable',
  storeNotFoundTip: 'Cette URL n’est pas active ou le nom de marque est incorrect.',
  openStoreCta: 'Ouvrir votre boutique gratuitement',
  noProducts: 'Pas encore de produits',
  homeNav: 'Accueil',
  pageNotFound: 'Page introuvable',
  pageNotFoundTip: 'Cette page n’est pas publiée ou n’existe pas.',
  backHome: 'Retour à l’accueil',
  productFallback: 'Produit',
  trialEnded: 'L’essai est terminé. Achats temporairement indisponibles.',
  productsNav: 'Tous les produits',
  aboutNav: 'À propos',
  errCancelled: 'Paiement annulé. Vous pouvez réessayer.',
  errCvsRequired: 'Veuillez d’abord choisir un magasin 7-11',
  errMapRequired: 'Choisissez un magasin 7-11 sur la carte',
  errCollectionMismatch: 'Le paramètre d’encaissement doit correspondre au paiement',
  errAmountLimit: 'Commandes 7-11 limitées à NT$ 20,000',
  errStripeUnavailable: 'Paiement par carte indisponible. Réessayez plus tard ou payez à la livraison.',
  errStock: 'Stock insuffisant',
  storeFallback: 'Ma boutique',
  browseProducts: 'Voir les produits',
  slideN: 'Diapositive {n}',
  editingPrefix: 'Édition ·',
  contactNav: 'Nous contacter',
  shippingPage: 'Politique de livraison',
  returnsPage: 'Retours',
  aboutBody: '{name} choisit chaque produit pour une meilleure expérience au quotidien.\n\nUn bon produit mérite une vraie présentation — découvrez la marque ici.',
  contactBody: 'Besoin d’aide ? Laissez une note sur la commande, ou un e-mail / téléphone valide au paiement. Nous répondrons dès que possible.\n\nBoutique : {name}',
  shippingBody: 'Les boutiques qui expédient depuis Taïwan peuvent proposer le retrait 7-11 (y compris contre remboursement) ou la livraison à domicile. Les autres proposent aujourd’hui domicile et paiement par carte. Frais et délais : selon le marchand.',
  returnsBody: 'Si l’article est défectueux ou ne correspond pas à la description, contactez-nous rapidement. Les articles non ouverts / non utilisés sont examinés au cas par cas.',
}

export const checkoutCopyByLocale: Record<Locale, CheckoutCopy> = {
  'zh-TW': zhTW,
  'zh-CN': zhCN,
  en,
  ko,
  ja,
  vi,
  es,
  pt,
  de,
  fr,
}

export function getCheckoutCopy(locale: Locale): CheckoutCopy {
  return checkoutCopyByLocale[locale] || checkoutCopyByLocale.en
}
