import type { Locale } from './i18n'
import { pickCopy } from './i18n/pageCopy'

export type MerchantDashCopy = {
  title: string
  subtitle: string
  design: string
  pages: string
  orders: string
  logistics: string
  preview: string
  billing: string
  trialExpired: string
  activatePlan: string
  thenOperate: string
  trialLeft: string
  loading: string
  noStore: string
  goRegister: string
  storeName: string
  publicUrl: string
  productCount: string
  countUnit: string
  editProduct: string
  newProduct: string
  cannotAdd: string
  name: string
  price: string
  category: string
  stock: string
  imageUrl: string
  desc: string
  saving: string
  update: string
  publish: string
  cancel: string
  listed: string
  empty: string
  general: string
  stockLabel: string
  edit: string
  del: string
  confirmRemove: string
  loadFail: string
  saveFail: string
  saved: string
  created: string
  deleted: string
  deleteFail: string
}

const zhTW: MerchantDashCopy = {
  title: '我的商店',
  subtitle: '上架商品後，客人就能在你的商店頁選購、加入購物車、結帳。',
  design: '拖拉設計店面',
  pages: '商店頁面',
  orders: '訂單與寄件',
  logistics: '收款／物流',
  preview: '預覽商店頁',
  billing: '方案與試用',
  trialExpired: '試用已結束，商店已暫停接單與上架。請先',
  activatePlan: '開通方案',
  thenOperate: '後繼續營業。',
  trialLeft: '免費試用剩餘 {days} 天。試用期間客人可刷卡購物；到期後需訂閱才能繼續。',
  loading: '載入中...',
  noStore: '找不到商店，請先完成註冊開店',
  goRegister: '去註冊開店 →',
  storeName: '商店名稱',
  publicUrl: '公開網址',
  productCount: '上架商品',
  countUnit: '件',
  editProduct: '編輯商品',
  newProduct: '上架新商品',
  cannotAdd: '試用已結束，無法上架。請先到方案頁開通。',
  name: '商品名稱',
  price: '價格（NT$）',
  category: '分類',
  stock: '庫存',
  imageUrl: '圖片網址',
  desc: '描述',
  saving: '儲存中...',
  update: '更新商品',
  publish: '上架商品',
  cancel: '取消',
  listed: '已上架商品',
  empty: '還沒有商品，先從左側上架第一件吧',
  general: '一般',
  stockLabel: '庫存',
  edit: '編輯',
  del: '刪除',
  confirmRemove: '確定下架「{name}」？',
  loadFail: '載入失敗',
  saveFail: '儲存失敗',
  saved: '商品已更新',
  created: '商品已上架到你的商店',
  deleted: '商品已刪除',
  deleteFail: '刪除失敗',
}

const zhCN: MerchantDashCopy = {
  ...zhTW,
  title: '我的商店',
  subtitle: '上架商品后，客人就能在你的商店页选购、加入购物车、结账。',
  design: '拖放设计店面',
  pages: '商店页面',
  orders: '订单与寄件',
  logistics: '收款／物流',
  preview: '预览商店页',
  billing: '方案与试用',
  trialExpired: '试用已结束，商店已暂停接单与上架。请先',
  activatePlan: '开通方案',
  thenOperate: '后继续营业。',
  trialLeft: '免费试用剩余 {days} 天。试用期间客人可刷卡购物；到期后需订阅才能继续。',
  loading: '加载中...',
  noStore: '找不到商店，请先完成注册开店',
  goRegister: '去注册开店 →',
  storeName: '商店名称',
  publicUrl: '公开网址',
  productCount: '上架商品',
  countUnit: '件',
  editProduct: '编辑商品',
  newProduct: '上架新商品',
  cannotAdd: '试用已结束，无法上架。请先到方案页开通。',
  name: '商品名称',
  price: '价格（NT$）',
  category: '分类',
  stock: '库存',
  imageUrl: '图片网址',
  desc: '描述',
  saving: '保存中...',
  update: '更新商品',
  publish: '上架商品',
  cancel: '取消',
  listed: '已上架商品',
  empty: '还没有商品，先从左侧上架第一件吧',
  general: '一般',
  stockLabel: '库存',
  edit: '编辑',
  del: '删除',
  confirmRemove: '确定下架「{name}」？',
  loadFail: '加载失败',
  saveFail: '保存失败',
  saved: '商品已更新',
  created: '商品已上架到你的商店',
  deleted: '商品已删除',
  deleteFail: '删除失败',
}

const en: MerchantDashCopy = {
  title: 'My store',
  subtitle: 'Once you list products, shoppers can browse, add to cart, and check out on your storefront.',
  design: 'Design storefront',
  pages: 'Store pages',
  orders: 'Orders & shipping',
  logistics: 'Payments / logistics',
  preview: 'Preview store',
  billing: 'Plans & trial',
  trialExpired: 'Trial ended. Ordering and listing are paused. Please',
  activatePlan: 'activate a plan',
  thenOperate: 'to keep operating.',
  trialLeft: '{days} days left in your free trial. Shoppers can pay by card during trial; subscribe after it ends.',
  loading: 'Loading...',
  noStore: 'Store not found. Please finish sign-up first.',
  goRegister: 'Create a store →',
  storeName: 'Store name',
  publicUrl: 'Public URL',
  productCount: 'Listed products',
  countUnit: '',
  editProduct: 'Edit product',
  newProduct: 'Add a product',
  cannotAdd: 'Trial ended. Activate a plan before listing products.',
  name: 'Product name',
  price: 'Price (NT$)',
  category: 'Category',
  stock: 'Stock',
  imageUrl: 'Image URL',
  desc: 'Description',
  saving: 'Saving...',
  update: 'Update product',
  publish: 'List product',
  cancel: 'Cancel',
  listed: 'Listed products',
  empty: 'No products yet. Add the first one on the left.',
  general: 'General',
  stockLabel: 'Stock',
  edit: 'Edit',
  del: 'Delete',
  confirmRemove: 'Remove “{name}”?',
  loadFail: 'Failed to load',
  saveFail: 'Could not save',
  saved: 'Product updated',
  created: 'Product listed on your store',
  deleted: 'Product deleted',
  deleteFail: 'Could not delete',
}

const ko: MerchantDashCopy = {
  ...en,
  title: '내 스토어',
  subtitle: '상품을 올리면 손님은 스토어에서 담고 결제할 수 있습니다.',
  design: '스토어 디자인',
  pages: '스토어 페이지',
  orders: '주문 및 발송',
  logistics: '결제／물류',
  preview: '스토어 미리보기',
  billing: '요금제 및 체험',
  trialExpired: '체험이 종료되어 주문과 등록이 중지되었습니다.',
  activatePlan: '요금제 활성화',
  thenOperate: '후 계속 운영하세요.',
  trialLeft: '무료 체험 {days}일 남음. 체험 중 손님은 카드 결제 가능하며, 종료 후 구독이 필요합니다.',
  loading: '로딩 중...',
  noStore: '스토어를 찾을 수 없습니다. 먼저 가입을 완료하세요.',
  goRegister: '스토어 만들기 →',
  storeName: '스토어 이름',
  publicUrl: '공개 URL',
  productCount: '등록 상품',
  editProduct: '상품 수정',
  newProduct: '새 상품 등록',
  cannotAdd: '체험이 종료되어 등록할 수 없습니다. 요금제 페이지에서 활성화하세요.',
  name: '상품명',
  price: '가격 (NT$)',
  category: '카테고리',
  stock: '재고',
  imageUrl: '이미지 URL',
  desc: '설명',
  saving: '저장 중...',
  update: '상품 업데이트',
  publish: '상품 등록',
  cancel: '취소',
  listed: '등록된 상품',
  empty: '아직 상품이 없습니다. 왼쪽에서 첫 상품을 등록하세요.',
  general: '일반',
  stockLabel: '재고',
  edit: '수정',
  del: '삭제',
  confirmRemove: '“{name}”을(를) 내릴까요?',
  loadFail: '불러오기 실패',
  saveFail: '저장 실패',
  saved: '상품이 업데이트되었습니다',
  created: '상품이 스토어에 등록되었습니다',
  deleted: '상품이 삭제되었습니다',
  deleteFail: '삭제 실패',
}

const ja: MerchantDashCopy = {
  ...en,
  title: 'マイストア',
  subtitle: '商品を掲載すると、お客様はストアでカートに入れて決済できます。',
  design: 'ストアをデザイン',
  pages: 'ストアページ',
  orders: '注文と発送',
  logistics: '決済／物流',
  preview: 'ストアをプレビュー',
  billing: 'プランとトライアル',
  trialExpired: 'トライアル終了のため、受注と掲載を停止しています。',
  activatePlan: 'プランを有効化',
  thenOperate: 'して運営を続けてください。',
  trialLeft: '無料トライアル残り {days} 日。期間中はカード決済が可能で、終了後はサブスクが必要です。',
  loading: '読み込み中...',
  noStore: 'ストアが見つかりません。先に登録を完了してください。',
  goRegister: 'ストアを開く →',
  storeName: 'ストア名',
  publicUrl: '公開URL',
  productCount: '掲載商品',
  editProduct: '商品を編集',
  newProduct: '新商品を掲載',
  cannotAdd: 'トライアル終了のため掲載できません。プランページで有効化してください。',
  name: '商品名',
  price: '価格（NT$）',
  category: 'カテゴリ',
  stock: '在庫',
  imageUrl: '画像URL',
  desc: '説明',
  saving: '保存中...',
  update: '商品を更新',
  publish: '商品を掲載',
  cancel: 'キャンセル',
  listed: '掲載中の商品',
  empty: 'まだ商品がありません。左から最初の1点を掲載してください。',
  general: '一般',
  stockLabel: '在庫',
  edit: '編集',
  del: '削除',
  confirmRemove: '「{name}」を取り下げますか？',
  loadFail: '読み込み失敗',
  saveFail: '保存に失敗',
  saved: '商品を更新しました',
  created: '商品をストアに掲載しました',
  deleted: '商品を削除しました',
  deleteFail: '削除に失敗',
}

const vi: MerchantDashCopy = {
  ...en,
  title: 'Cửa hàng của tôi',
  subtitle: 'Sau khi đăng sản phẩm, khách có thể chọn, thêm vào giỏ và thanh toán.',
  design: 'Thiết kế cửa hàng',
  pages: 'Trang cửa hàng',
  orders: 'Đơn & gửi hàng',
  logistics: 'Thanh toán／vận chuyển',
  preview: 'Xem cửa hàng',
  billing: 'Gói & dùng thử',
  trialExpired: 'Hết dùng thử. Đã tạm dừng nhận đơn và đăng bán. Vui lòng',
  activatePlan: 'kích hoạt gói',
  thenOperate: 'để tiếp tục.',
  trialLeft: 'Còn {days} ngày dùng thử. Khách có thể trả thẻ trong thời gian này; hết hạn cần đăng ký.',
  loading: 'Đang tải...',
  noStore: 'Không tìm thấy cửa hàng. Hãy hoàn tất đăng ký.',
  goRegister: 'Tạo cửa hàng →',
  storeName: 'Tên cửa hàng',
  publicUrl: 'URL công khai',
  productCount: 'Sản phẩm đã đăng',
  editProduct: 'Sửa sản phẩm',
  newProduct: 'Thêm sản phẩm',
  cannotAdd: 'Hết dùng thử, không đăng được. Hãy kích hoạt gói.',
  name: 'Tên sản phẩm',
  price: 'Giá (NT$)',
  category: 'Danh mục',
  stock: 'Tồn kho',
  imageUrl: 'URL ảnh',
  desc: 'Mô tả',
  saving: 'Đang lưu...',
  update: 'Cập nhật',
  publish: 'Đăng sản phẩm',
  cancel: 'Hủy',
  listed: 'Sản phẩm đã đăng',
  empty: 'Chưa có sản phẩm. Thêm cái đầu tiên bên trái.',
  general: 'Chung',
  stockLabel: 'Tồn',
  edit: 'Sửa',
  del: 'Xóa',
  confirmRemove: 'Gỡ “{name}”?',
  loadFail: 'Tải thất bại',
  saveFail: 'Lưu thất bại',
  saved: 'Đã cập nhật sản phẩm',
  created: 'Đã đăng sản phẩm',
  deleted: 'Đã xóa sản phẩm',
  deleteFail: 'Xóa thất bại',
}

const es: MerchantDashCopy = {
  ...en,
  title: 'Mi tienda',
  subtitle: 'Cuando publiques productos, los clientes podrán comprar en tu tienda.',
  design: 'Diseñar tienda',
  pages: 'Páginas',
  orders: 'Pedidos y envíos',
  logistics: 'Pagos / logística',
  preview: 'Ver tienda',
  billing: 'Planes y prueba',
  trialExpired: 'La prueba terminó. Pedidos y publicaciones están en pausa. Por favor',
  activatePlan: 'activa un plan',
  thenOperate: 'para seguir operando.',
  trialLeft: 'Quedan {days} días de prueba. Los clientes pueden pagar con tarjeta; al terminar hay que suscribirse.',
  loading: 'Cargando...',
  noStore: 'No se encontró la tienda. Completa el registro.',
  goRegister: 'Crear tienda →',
  storeName: 'Nombre de la tienda',
  publicUrl: 'URL pública',
  productCount: 'Productos publicados',
  editProduct: 'Editar producto',
  newProduct: 'Añadir producto',
  cannotAdd: 'La prueba terminó. Activa un plan para publicar.',
  name: 'Nombre del producto',
  price: 'Precio (NT$)',
  category: 'Categoría',
  stock: 'Stock',
  imageUrl: 'URL de imagen',
  desc: 'Descripción',
  saving: 'Guardando...',
  update: 'Actualizar',
  publish: 'Publicar',
  cancel: 'Cancelar',
  listed: 'Productos publicados',
  empty: 'Aún no hay productos. Añade el primero a la izquierda.',
  general: 'General',
  stockLabel: 'Stock',
  edit: 'Editar',
  del: 'Eliminar',
  confirmRemove: '¿Quitar “{name}”?',
  loadFail: 'Error al cargar',
  saveFail: 'No se pudo guardar',
  saved: 'Producto actualizado',
  created: 'Producto publicado',
  deleted: 'Producto eliminado',
  deleteFail: 'No se pudo eliminar',
}

const pt: MerchantDashCopy = {
  ...en,
  title: 'Minha loja',
  subtitle: 'Depois de publicar produtos, os clientes podem comprar na sua loja.',
  design: 'Design da loja',
  pages: 'Páginas da loja',
  orders: 'Pedidos e envio',
  logistics: 'Pagamentos / logística',
  preview: 'Ver loja',
  billing: 'Planos e teste',
  trialExpired: 'O teste acabou. Pedidos e listagens estão pausados. Por favor',
  activatePlan: 'ative um plano',
  thenOperate: 'para continuar.',
  trialLeft: '{days} dias restantes no teste. Clientes podem pagar com cartão; depois é preciso assinar.',
  loading: 'Carregando...',
  noStore: 'Loja não encontrada. Conclua o cadastro.',
  goRegister: 'Criar loja →',
  storeName: 'Nome da loja',
  publicUrl: 'URL pública',
  productCount: 'Produtos listados',
  editProduct: 'Editar produto',
  newProduct: 'Adicionar produto',
  cannotAdd: 'Teste encerrado. Ative um plano para listar.',
  name: 'Nome do produto',
  price: 'Preço (NT$)',
  category: 'Categoria',
  stock: 'Estoque',
  imageUrl: 'URL da imagem',
  desc: 'Descrição',
  saving: 'Salvando...',
  update: 'Atualizar',
  publish: 'Listar produto',
  cancel: 'Cancelar',
  listed: 'Produtos listados',
  empty: 'Ainda sem produtos. Adicione o primeiro à esquerda.',
  general: 'Geral',
  stockLabel: 'Estoque',
  edit: 'Editar',
  del: 'Excluir',
  confirmRemove: 'Remover “{name}”?',
  loadFail: 'Falha ao carregar',
  saveFail: 'Falha ao salvar',
  saved: 'Produto atualizado',
  created: 'Produto listado',
  deleted: 'Produto excluído',
  deleteFail: 'Falha ao excluir',
}

const de: MerchantDashCopy = {
  ...en,
  title: 'Mein Shop',
  subtitle: 'Wenn Sie Produkte listen, können Kunden in Ihrem Shop kaufen.',
  design: 'Shop gestalten',
  pages: 'Shop-Seiten',
  orders: 'Bestellungen & Versand',
  logistics: 'Zahlungen / Logistik',
  preview: 'Shop ansehen',
  billing: 'Tarife & Test',
  trialExpired: 'Testphase vorbei. Bestellungen und Listings sind pausiert.',
  activatePlan: 'Tarif aktivieren',
  thenOperate: 'um weiterzumachen.',
  trialLeft: 'Noch {days} Tage Testphase. Kunden können mit Karte zahlen; danach Abo nötig.',
  loading: 'Wird geladen...',
  noStore: 'Shop nicht gefunden. Bitte Registrierung abschließen.',
  goRegister: 'Shop erstellen →',
  storeName: 'Shopname',
  publicUrl: 'Öffentliche URL',
  productCount: 'Gelistete Produkte',
  editProduct: 'Produkt bearbeiten',
  newProduct: 'Produkt hinzufügen',
  cannotAdd: 'Testphase vorbei. Aktivieren Sie einen Tarif zum Listen.',
  name: 'Produktname',
  price: 'Preis (NT$)',
  category: 'Kategorie',
  stock: 'Lager',
  imageUrl: 'Bild-URL',
  desc: 'Beschreibung',
  saving: 'Speichern...',
  update: 'Aktualisieren',
  publish: 'Produkt listen',
  cancel: 'Abbrechen',
  listed: 'Gelistete Produkte',
  empty: 'Noch keine Produkte. Legen Sie links das erste an.',
  general: 'Allgemein',
  stockLabel: 'Lager',
  edit: 'Bearbeiten',
  del: 'Löschen',
  confirmRemove: '„{name}“ entfernen?',
  loadFail: 'Laden fehlgeschlagen',
  saveFail: 'Speichern fehlgeschlagen',
  saved: 'Produkt aktualisiert',
  created: 'Produkt gelistet',
  deleted: 'Produkt gelöscht',
  deleteFail: 'Löschen fehlgeschlagen',
}

const fr: MerchantDashCopy = {
  ...en,
  title: 'Ma boutique',
  subtitle: 'Une fois les produits publiés, les clients peuvent acheter sur votre boutique.',
  design: 'Concevoir la boutique',
  pages: 'Pages boutique',
  orders: 'Commandes et envois',
  logistics: 'Paiements / logistique',
  preview: 'Aperçu boutique',
  billing: 'Offres et essai',
  trialExpired: 'Essai terminé. Commandes et publications en pause. Veuillez',
  activatePlan: 'activer une offre',
  thenOperate: 'pour continuer.',
  trialLeft: 'Il reste {days} jours d’essai. Les clients peuvent payer par carte ; ensuite, un abonnement est requis.',
  loading: 'Chargement...',
  noStore: 'Boutique introuvable. Terminez l’inscription.',
  goRegister: 'Créer une boutique →',
  storeName: 'Nom de la boutique',
  publicUrl: 'URL publique',
  productCount: 'Produits publiés',
  editProduct: 'Modifier le produit',
  newProduct: 'Ajouter un produit',
  cannotAdd: 'Essai terminé. Activez une offre pour publier.',
  name: 'Nom du produit',
  price: 'Prix (NT$)',
  category: 'Catégorie',
  stock: 'Stock',
  imageUrl: 'URL de l’image',
  desc: 'Description',
  saving: 'Enregistrement...',
  update: 'Mettre à jour',
  publish: 'Publier',
  cancel: 'Annuler',
  listed: 'Produits publiés',
  empty: 'Pas encore de produits. Ajoutez le premier à gauche.',
  general: 'Général',
  stockLabel: 'Stock',
  edit: 'Modifier',
  del: 'Supprimer',
  confirmRemove: 'Retirer « {name} » ?',
  loadFail: 'Échec du chargement',
  saveFail: 'Échec de l’enregistrement',
  saved: 'Produit mis à jour',
  created: 'Produit publié',
  deleted: 'Produit supprimé',
  deleteFail: 'Échec de la suppression',
}

export function getMerchantDashCopy(locale: Locale): MerchantDashCopy {
  return pickCopy(locale, { 'zh-TW': zhTW, 'zh-CN': zhCN, en, ko, ja, vi, es, pt, de, fr })
}
