import type { Locale } from './i18n'

export type MerchantOpsCopy = {
  eyebrow: string
  title: string
  subtitle: string
  guideLink: string
  backStore: string
  loading: string
  empty: string
  orderLabel: string
  recipient: string
  shipping: string
  seven: string
  home: string
  shipmentCode: string
  logisticsError: string
  createShipment: string
  creating: string
  createFail: string
  shipmentReady: string
  loadFail: string
  logEyebrow: string
  logTitle: string
  logSubtitle: string
  guideCta: string
  marketTitle: string
  marketDesc: string
  marketTw: string
  marketIntl: string
  marketTwSaved: string
  marketIntlSaved: string
  ecpayTitle: string
  ecpayDesc: string
  ecpayLogin: string
  ecpayHow: string
  ecpayHome: string
  flowTitle: string
  step1Title: string
  step1Desc: string
  step1Link: string
  step2Title: string
  step2Desc: string
  step2Mail: string
  step2Guide: string
  step3Title: string
  step3Desc: string
  warnPending: string
  docsTitle: string
  docsGuide: string
  docsOrders: string
  keysTitle: string
  keysDesc: string
  expand: string
  collapse: string
  statusReady: string
  statusConfigured: string
  statusNone: string
  statusLabel: string
  env: string
  envStage: string
  envProd: string
  subtype: string
  subtypeAuto: string
  senderName: string
  senderPhone: string
  keepEmpty: string
  saveKeys: string
  saving: string
  saved: string
  saveFail: string
  ibonHow: string
  noShipmentYet: string
  statusPaid: string
  statusCod: string
  statusPending: string
  statusFailed: string
  statusCancelled: string
  errPaymentRequired: string
  errEcpayNotConfigured: string
  errNotCvs: string
  errCvsRequired: string
  errAmountLimit: string
  errNoStore: string
}

const zhTW: MerchantOpsCopy = {
  eyebrow: 'ORDERS',
  title: '訂單與寄件',
  subtitle: '7-11 取貨訂單會顯示 ibon 寄件代碼。請到超商 ibon → 交貨便 → 輸入代碼列印寄件單。尚未開通？請先閱讀開通說明，完成綠界申請後再來信協助串接。',
  guideLink: '開通說明',
  backStore: '回我的商店',
  loading: '載入中...',
  empty: '尚無訂單',
  orderLabel: '訂單',
  recipient: '收件',
  shipping: '配送',
  seven: '7-11 取貨',
  home: '宅配／其他',
  shipmentCode: 'ibon 寄件代碼',
  logisticsError: '物流提示',
  createShipment: '產生 7-11 寄件代碼',
  creating: '產生中...',
  createFail: '產生失敗',
  shipmentReady: '訂單 #{id} 寄件代碼：{code}',
  loadFail: '載入失敗',
  logEyebrow: 'PAYMENTS / LOGISTICS',
  logTitle: '收款／物流設定',
  logSubtitle: '7-11 超商取貨為選配。若要開通，請完成綠界物流申請後再依說明串接；不開通也不影響宅配與信用卡結帳。',
  guideCta: '完整操作說明',
  marketTitle: '出貨市場',
  marketDesc: '決定結帳要不要顯示台灣超商取貨／貨到付款。網站介面語系與此無關。',
  marketTw: '台灣出貨（可選配 7-11）',
  marketIntl: '國際出貨（僅宅配＋卡）',
  marketTwSaved: '已設為台灣出貨（可選配 7-11）。',
  marketIntlSaved: '已設為國際出貨（僅宅配＋信用卡）。',
  ecpayTitle: '綠界申請入口',
  ecpayDesc: '請先至綠界完成賣家註冊／登入，並申請物流（須一併申請金流）。審核通過後再到「系統開發管理 → 系統介接設定」取得商店代號與金鑰。',
  ecpayLogin: '綠界賣家註冊／登入',
  ecpayHow: '綠界：如何申請物流',
  ecpayHome: '綠界官網',
  flowTitle: '開通流程',
  step1Title: '至綠界申請 7-11 物流',
  step1Desc: '新戶請同時勾選金流與物流；舊戶請至「驗證／服務」加開。建議選 C2C（UNIMARTC2C）。通過後至「系統介接設定」複製 MerchantID／HashKey／HashIV。',
  step1Link: '開啟綠界賣家註冊／登入 →',
  step2Title: '提供資料，請 ARVIX 協助串接',
  step2Desc: '請來信提供商店名稱、Email、MerchantID、環境（測試／正式）及需求項目。請勿於一般郵件直接傳送完整 Hash 金鑰。',
  step2Mail: '來信申請串接',
  step2Guide: '查看完整操作說明',
  step3Title: '串接完成後即可使用',
  step3Desc: '貨到付款於下單後產生寄件代碼；刷卡取貨於付款成功後產生。C2C 可至 ibon 交貨便列印；B2C 請依綠界大宗流程出貨。',
  warnPending: '尚未完成串接前，無法使用官方電子地圖，亦無法產生寄件代碼。宅配與信用卡付款不受影響。',
  docsTitle: '文件與入口',
  docsGuide: '完整操作說明（可列印／另存 PDF）',
  docsOrders: '訂單與寄件',
  keysTitle: '進階設定：金鑰欄位',
  keysDesc: '建議先來信由客服協助。若客服請您自行填寫金鑰，再展開此區。',
  expand: '展開',
  collapse: '收合',
  statusReady: '可選店＋寄件碼',
  statusConfigured: '已有 MerchantID',
  statusNone: '尚未設定',
  statusLabel: '狀態',
  env: '環境',
  envStage: '測試 stage',
  envProd: '正式 production',
  subtype: 'LogisticsSubType',
  subtypeAuto: '自動',
  senderName: '寄件人姓名（綠界）',
  senderPhone: '寄件人手機（綠界）',
  keepEmpty: '留空＝不變更',
  saveKeys: '儲存金鑰',
  saving: '儲存中...',
  saved: '已儲存。建議再通知客服工程師確認串接狀態。',
  saveFail: '儲存失敗',
  ibonHow: '至 7-11 ibon → 購物／寄貨 → 交貨便 → 寄件 → 輸入此代碼 → 列印貼單寄出',
  noShipmentYet: '尚未產生寄件代碼',
  statusPaid: '已付款',
  statusCod: '貨到付款',
  statusPending: '待付款',
  statusFailed: '失敗',
  statusCancelled: '已取消',
  errPaymentRequired: '訂單尚未付款，無法產生寄件代碼',
  errEcpayNotConfigured: '請先完成綠界物流設定',
  errNotCvs: '此訂單不是超商取貨',
  errCvsRequired: '缺少門市代碼',
  errAmountLimit: '金額超過超商取貨上限',
  errNoStore: '尚未建立商店',
}

const zhCN: MerchantOpsCopy = {
  eyebrow: 'ORDERS',
  title: '订单与寄件',
  subtitle: '7-11 取货订单会显示寄件代码。请到超商 ibon → 交货便 → 输入代码打印寄件单。尚未开通？请先阅读开通说明，完成绿界申请后再来信协助串接。',
  guideLink: '开通说明',
  backStore: '回我的商店',
  loading: '加载中...',
  empty: '尚无订单',
  orderLabel: '订单',
  recipient: '收件',
  shipping: '配送',
  seven: '7-11 取货',
  home: '宅配／其他',
  shipmentCode: 'ibon 寄件代码',
  logisticsError: '物流提示',
  createShipment: '产生 7-11 寄件代码',
  creating: '产生中...',
  createFail: '产生失败',
  shipmentReady: '订单 #{id} 寄件代码：{code}',
  loadFail: '加载失败',
  logEyebrow: 'PAYMENTS / LOGISTICS',
  logTitle: '收款／物流设定',
  logSubtitle: '7-11 超商取货为选配。若要开通，请完成绿界物流申请后再依说明串接；不开通也不影响宅配与信用卡结账。',
  guideCta: '完整操作说明',
  marketTitle: '出货市场',
  marketDesc: '决定结账要不要显示台湾超商取货／货到付款。网站界面语系与此无关。',
  marketTw: '台湾出货（可选配 7-11）',
  marketIntl: '国际出货（仅宅配＋卡）',
  marketTwSaved: '已设为台湾出货（可选配 7-11）。',
  marketIntlSaved: '已设为国际出货（仅宅配＋信用卡）。',
  ecpayTitle: '绿界申请入口',
  ecpayDesc: '请先至绿界完成卖家注册／登录，并申请物流（须一并申请金流）。审核通过后再到「系统开发管理 → 系统介接设定」取得商店代号与密钥。',
  ecpayLogin: '绿界卖家注册／登录',
  ecpayHow: '绿界：如何申请物流',
  ecpayHome: '绿界官网',
  flowTitle: '开通流程',
  step1Title: '至绿界申请 7-11 物流',
  step1Desc: '新户请同时勾选金流与物流；旧户请至「验证／服务」加开。建议选 C2C（UNIMARTC2C）。通过后至「系统介接设定」复制 MerchantID／HashKey／HashIV。',
  step1Link: '开启绿界卖家注册／登录 →',
  step2Title: '提供资料，请 ARVIX 协助串接',
  step2Desc: '请来信提供商店名称、Email、MerchantID、环境（测试／正式）及需求项目。请勿于一般邮件直接传送完整 Hash 密钥。',
  step2Mail: '来信申请串接',
  step2Guide: '查看完整操作说明',
  step3Title: '串接完成后即可使用',
  step3Desc: '货到付款于下单后产生寄件代码；刷卡取货于付款成功后产生。C2C 可至 ibon 交货便打印；B2C 请依绿界大宗流程出货。',
  warnPending: '尚未完成串接前，无法使用官方电子地图，亦无法产生寄件代码。宅配与信用卡付款不受影响。',
  docsTitle: '文件与入口',
  docsGuide: '完整操作说明（可打印／另存 PDF）',
  docsOrders: '订单与寄件',
  keysTitle: '进阶设定：密钥栏位',
  keysDesc: '建议先来信由客服协助。若客服请您自行填写密钥，再展开此区。',
  expand: '展开',
  collapse: '收合',
  statusReady: '可选店＋寄件码',
  statusConfigured: '已有 MerchantID',
  statusNone: '尚未设定',
  statusLabel: '状态',
  env: '环境',
  envStage: '测试 stage',
  envProd: '正式 production',
  subtype: 'LogisticsSubType',
  subtypeAuto: '自動',
  senderName: '寄件人姓名（绿界）',
  senderPhone: '寄件人手机（绿界）',
  keepEmpty: '留空＝不变更',
  saveKeys: '储存密钥',
  saving: '储存中...',
  saved: '已储存。建议再通知客服工程师确认串接状态。',
  saveFail: '储存失败',
  ibonHow: '至 7-11 ibon → 购物／寄货 → 交货便 → 寄件 → 输入此代码 → 打印贴单寄出',
  noShipmentYet: '尚未产生寄件代码',
  statusPaid: '已付款',
  statusCod: '货到付款',
  statusPending: '待付款',
  statusFailed: '失败',
  statusCancelled: '已取消',
  errPaymentRequired: '订单尚未付款，无法产生寄件代码',
  errEcpayNotConfigured: '请先完成绿界物流设定',
  errNotCvs: '此订单不是超商取货',
  errCvsRequired: '缺少门市代码',
  errAmountLimit: '金额超过超商取货上限',
  errNoStore: '尚未建立商店',
}

const en: MerchantOpsCopy = {
  eyebrow: 'ORDERS',
  title: 'Orders & shipping',
  subtitle: '7-11 pickup orders show an ibon shipment code. At 7-11 ibon → parcel drop-off → enter the code to print the label. Not enabled yet? Read the setup guide, finish ECPay application, then email us for integration help.',
  guideLink: 'Setup guide',
  backStore: 'Back to my store',
  loading: 'Loading...',
  empty: 'No orders yet',
  orderLabel: 'Order',
  recipient: 'Recipient',
  shipping: 'Shipping',
  seven: '7-11 pickup',
  home: 'Home delivery',
  shipmentCode: 'ibon shipment code',
  logisticsError: 'Logistics note',
  createShipment: 'Create 7-11 shipment code',
  creating: 'Creating...',
  createFail: 'Could not create shipment',
  shipmentReady: 'Order #{id} shipment code: {code}',
  loadFail: 'Failed to load',
  logEyebrow: 'PAYMENTS / LOGISTICS',
  logTitle: 'Payments / logistics',
  logSubtitle: '7-11 pickup is optional. To enable it, finish ECPay logistics then follow the guide. Home delivery and card checkout work without it.',
  guideCta: 'Full guide',
  marketTitle: 'Shipping market',
  marketDesc: 'Controls whether Taiwan convenience-store pickup / COD appear at checkout. Site language is separate.',
  marketTw: 'Taiwan shipping (optional 7-11)',
  marketIntl: 'International (home + card only)',
  marketTwSaved: 'Set to Taiwan shipping (optional 7-11).',
  marketIntlSaved: 'Set to international shipping (home + card only).',
  ecpayTitle: 'ECPay application',
  ecpayDesc: 'Register/login on ECPay and apply for logistics (payments required too). After approval, copy MerchantID / HashKey / HashIV from system integration settings.',
  ecpayLogin: 'ECPay seller login',
  ecpayHow: 'ECPay: how to apply logistics',
  ecpayHome: 'ECPay website',
  flowTitle: 'Setup steps',
  step1Title: 'Apply for 7-11 logistics on ECPay',
  step1Desc: 'New accounts should enable payments + logistics; existing accounts add logistics under verification/services. Prefer C2C (UNIMARTC2C). Then copy MerchantID / HashKey / HashIV.',
  step1Link: 'Open ECPay seller login →',
  step2Title: 'Send details for ARVIX integration help',
  step2Desc: 'Email your store name, email, MerchantID, environment (stage/production), and needs. Do not send full Hash secrets in ordinary email.',
  step2Mail: 'Email for integration',
  step2Guide: 'View full guide',
  step3Title: 'Ready after integration',
  step3Desc: 'COD creates a shipment code after order; card pickup creates it after payment. C2C: print via ibon; B2C: follow ECPay bulk shipping.',
  warnPending: 'Before integration, official map pickup and shipment codes are unavailable. Home delivery and card payment still work.',
  docsTitle: 'Docs & links',
  docsGuide: 'Full guide (print / save PDF)',
  docsOrders: 'Orders & shipping',
  keysTitle: 'Advanced: API keys',
  keysDesc: 'Prefer emailing support first. Expand this only if support asked you to enter keys yourself.',
  expand: 'Expand',
  collapse: 'Collapse',
  statusReady: 'Map + shipment ready',
  statusConfigured: 'MerchantID set',
  statusNone: 'Not configured',
  statusLabel: 'Status',
  env: 'Environment',
  envStage: 'Stage (test)',
  envProd: 'Production',
  subtype: 'LogisticsSubType',
  subtypeAuto: 'Auto',
  senderName: 'Sender name (ECPay)',
  senderPhone: 'Sender phone (ECPay)',
  keepEmpty: 'Leave blank = keep current',
  saveKeys: 'Save keys',
  saving: 'Saving...',
  saved: 'Saved. Ask support to confirm integration if needed.',
  saveFail: 'Save failed',
  ibonHow: 'At 7-11 ibon → Shopping/shipping → Parcel → Ship → enter this code → print & ship',
  noShipmentYet: 'No shipment code yet',
  statusPaid: 'Paid',
  statusCod: 'Cash on delivery',
  statusPending: 'Pending payment',
  statusFailed: 'Failed',
  statusCancelled: 'Cancelled',
  errPaymentRequired: 'Payment required before creating a shipment code',
  errEcpayNotConfigured: 'Configure ECPay logistics first',
  errNotCvs: 'This order is not convenience-store pickup',
  errCvsRequired: 'Missing store ID',
  errAmountLimit: 'Amount exceeds convenience-store limit',
  errNoStore: 'No store yet',
}

const ko: MerchantOpsCopy = {
  eyebrow: 'ORDERS',
  title: '주문 및 배송',
  subtitle: '7-11 픽업 주문에는 ibon 발송 코드가 표시됩니다. 편의점 ibon → 택배 접수 → 코드 입력 후 운송장을 인쇄하세요. 아직 미개통이면 설정 안내를 읽고 그린세계(ECPay) 신청 후 이메일로 연동을 요청하세요.',
  guideLink: '설정 안내',
  backStore: '내 스토어로',
  loading: '로딩 중...',
  empty: '주문이 없습니다',
  orderLabel: '주문',
  recipient: '수령인',
  shipping: '배송',
  seven: '7-11 픽업',
  home: '택배／기타',
  shipmentCode: 'ibon 발송 코드',
  logisticsError: '물류 안내',
  createShipment: '7-11 발송 코드 생성',
  creating: '생성 중...',
  createFail: '생성 실패',
  shipmentReady: '주문 #{id} 발송 코드: {code}',
  loadFail: '불러오기 실패',
  logEyebrow: 'PAYMENTS / LOGISTICS',
  logTitle: '결제／물류 설정',
  logSubtitle: '7-11 픽업은 선택 사항입니다. 사용하려면 ECPay 물류 신청 후 안내에 따라 연동하세요. 미연동 시에도 택배와 카드 결제는 가능합니다.',
  guideCta: '전체 안내',
  marketTitle: '출고 시장',
  marketDesc: '결제 화면에 대만 편의점 픽업／착불 표시 여부를 결정합니다. 사이트 언어와는 별개입니다.',
  marketTw: '대만 출고（7-11 선택）',
  marketIntl: '국제 출고（택배＋카드만）',
  marketTwSaved: '대만 출고로 설정되었습니다.',
  marketIntlSaved: '국제 출고（택배＋카드만）로 설정되었습니다.',
  ecpayTitle: 'ECPay 신청',
  ecpayDesc: 'ECPay에서 판매자 등록／로그인 후 물류를 신청하세요（결제도 함께 필요）. 승인 후 시스템 연동 설정에서 MerchantID／HashKey／HashIV를 복사하세요.',
  ecpayLogin: 'ECPay 판매자 로그인',
  ecpayHow: 'ECPay: 물류 신청 방법',
  ecpayHome: 'ECPay 웹사이트',
  flowTitle: '개통 절차',
  step1Title: 'ECPay에서 7-11 물류 신청',
  step1Desc: '신규는 결제+물류를 함께, 기존은 인증／서비스에서 물류를 추가하세요. C2C(UNIMARTC2C) 권장. 이후 MerchantID／HashKey／HashIV를 복사합니다.',
  step1Link: 'ECPay 판매자 로그인 열기 →',
  step2Title: '자료를 보내 ARVIX 연동 지원 요청',
  step2Desc: '스토어명, 이메일, MerchantID, 환경(테스트／정식), 요청 사항을 메일로 보내 주세요. 일반 메일에 전체 Hash 비밀키를 보내지 마세요.',
  step2Mail: '연동 신청 메일',
  step2Guide: '전체 안내 보기',
  step3Title: '연동 후 사용 가능',
  step3Desc: '착불은 주문 후, 카드 픽업은 결제 후 발송 코드가 생성됩니다. C2C는 ibon에서 인쇄, B2C는 ECPay 대량 출고를 따르세요.',
  warnPending: '연동 전에는 공식 지도 픽업과 발송 코드를 사용할 수 없습니다. 택배와 카드 결제는 가능합니다.',
  docsTitle: '문서 및 링크',
  docsGuide: '전체 안내（인쇄／PDF）',
  docsOrders: '주문 및 배송',
  keysTitle: '고급: API 키',
  keysDesc: '먼저 고객지원에 메일을 권장합니다. 지원팀이 직접 입력을 요청할 때만 펼치세요.',
  expand: '펼치기',
  collapse: '접기',
  statusReady: '매장 선택＋발송 코드 가능',
  statusConfigured: 'MerchantID 설정됨',
  statusNone: '미설정',
  statusLabel: '상태',
  env: '환경',
  envStage: '테스트 stage',
  envProd: '정식 production',
  subtype: 'LogisticsSubType',
  subtypeAuto: '자동',
  senderName: '발송인 성명（ECPay）',
  senderPhone: '발송인 휴대폰（ECPay）',
  keepEmpty: '비우면 변경 없음',
  saveKeys: '키 저장',
  saving: '저장 중...',
  saved: '저장되었습니다. 필요 시 지원팀에 연동 확인을 요청하세요.',
  saveFail: '저장 실패',
  ibonHow: '7-11 ibon → 쇼핑／배송 → 택배 → 발송 → 코드 입력 → 운송장 인쇄',
  noShipmentYet: '아직 발송 코드 없음',
  statusPaid: '결제 완료',
  statusCod: '착불',
  statusPending: '결제 대기',
  statusFailed: '실패',
  statusCancelled: '취소됨',
  errPaymentRequired: '결제 완료 후에만 발송 코드를 만들 수 있습니다',
  errEcpayNotConfigured: '먼저 ECPay 물류 설정을 완료하세요',
  errNotCvs: '편의점 수령 주문이 아닙니다',
  errCvsRequired: '점포 코드가 없습니다',
  errAmountLimit: '편의점 수령 한도를 초과했습니다',
  errNoStore: '아직 스토어가 없습니다',
}

const ja: MerchantOpsCopy = {
  eyebrow: 'ORDERS',
  title: '注文と発送',
  subtitle: '7-11 受取注文には ibon 出荷コードが表示されます。コンビニ ibon → 宅配便 → コード入力で伝票を印刷してください。未開通の場合は設定ガイドを読み、ECPay 申請後にメールで連携を依頼してください。',
  guideLink: '設定ガイド',
  backStore: 'マイストアへ',
  loading: '読み込み中...',
  empty: '注文はまだありません',
  orderLabel: '注文',
  recipient: '受取人',
  shipping: '配送',
  seven: '7-11 受取',
  home: '宅配／その他',
  shipmentCode: 'ibon 出荷コード',
  logisticsError: '物流メモ',
  createShipment: '7-11 出荷コードを発行',
  creating: '発行中...',
  createFail: '発行に失敗',
  shipmentReady: '注文 #{id} 出荷コード：{code}',
  loadFail: '読み込み失敗',
  logEyebrow: 'PAYMENTS / LOGISTICS',
  logTitle: '決済／物流設定',
  logSubtitle: '7-11 受取は任意です。使う場合は ECPay 物流申請後にガイドに従って連携してください。未連携でも宅配とカード決済は利用できます。',
  guideCta: '完全ガイド',
  marketTitle: '出荷市場',
  marketDesc: 'チェックアウトで台湾コンビニ受取／代金引換を出すかを決めます。サイト言語とは別です。',
  marketTw: '台湾出荷（7-11 任意）',
  marketIntl: '海外出荷（宅配＋カードのみ）',
  marketTwSaved: '台湾出荷に設定しました。',
  marketIntlSaved: '海外出荷（宅配＋カードのみ）に設定しました。',
  ecpayTitle: 'ECPay 申請',
  ecpayDesc: 'ECPay で出品者登録／ログインし物流を申請（決済も必要）。承認後、システム連携設定で MerchantID／HashKey／HashIV を取得します。',
  ecpayLogin: 'ECPay 出品者ログイン',
  ecpayHow: 'ECPay：物流の申請方法',
  ecpayHome: 'ECPay サイト',
  flowTitle: '開通手順',
  step1Title: 'ECPay で 7-11 物流を申請',
  step1Desc: '新規は決済＋物流、既存は認証／サービスで物流を追加。C2C（UNIMARTC2C）推奨。その後キーをコピー。',
  step1Link: 'ECPay 出品者ログインを開く →',
  step2Title: '資料を送り ARVIX に連携依頼',
  step2Desc: '店舗名、メール、MerchantID、環境（テスト／本番）、要望をメールで。通常メールに Hash 秘密鍵全文を送らないでください。',
  step2Mail: '連携依頼メール',
  step2Guide: '完全ガイドを見る',
  step3Title: '連携後に利用可能',
  step3Desc: '代金引換は注文後、カード受取は支払い後に出荷コード発行。C2C は ibon 印刷、B2C は ECPay 一括出荷に従ってください。',
  warnPending: '連携前は公式地図受取と出荷コードは使えません。宅配とカード決済は利用できます。',
  docsTitle: '資料とリンク',
  docsGuide: '完全ガイド（印刷／PDF）',
  docsOrders: '注文と発送',
  keysTitle: '上級：API キー',
  keysDesc: 'まずサポートへメールを推奨。指示があった場合のみ展開してください。',
  expand: '展開',
  collapse: '閉じる',
  statusReady: '店舗選択＋出荷コード可',
  statusConfigured: 'MerchantID 設定済',
  statusNone: '未設定',
  statusLabel: '状態',
  env: '環境',
  envStage: 'テスト stage',
  envProd: '本番 production',
  subtype: 'LogisticsSubType',
  subtypeAuto: '自動',
  senderName: '送り主氏名（ECPay）',
  senderPhone: '送り主携帯（ECPay）',
  keepEmpty: '空欄＝変更なし',
  saveKeys: 'キーを保存',
  saving: '保存中...',
  saved: '保存しました。必要ならサポートに連携確認を依頼してください。',
  saveFail: '保存失敗',
  ibonHow: '7-11 ibon → 買い物／発送 → 宅配便 → 発送 → コード入力 → 伝票印刷',
  noShipmentYet: '出荷コードはまだありません',
  statusPaid: '支払済',
  statusCod: '代金引換',
  statusPending: '支払待ち',
  statusFailed: '失敗',
  statusCancelled: 'キャンセル',
  errPaymentRequired: '支払い完了後に出荷コードを作成できます',
  errEcpayNotConfigured: '先にECPay物流設定を完了してください',
  errNotCvs: 'コンビニ受取の注文ではありません',
  errCvsRequired: '店舗コードがありません',
  errAmountLimit: 'コンビニ受取の上限を超えています',
  errNoStore: 'ストアがまだありません',
}

const vi: MerchantOpsCopy = {
  eyebrow: 'ORDERS',
  title: 'Đơn hàng & giao hàng',
  subtitle: 'Đơn nhận tại 7-11 sẽ có mã gửi ibon. Tại ibon → gửi hàng → nhập mã để in vận đơn. Chưa bật? Đọc hướng dẫn, hoàn tất ECPay rồi email để được hỗ trợ kết nối.',
  guideLink: 'Hướng dẫn',
  backStore: 'Về cửa hàng',
  loading: 'Đang tải...',
  empty: 'Chưa có đơn',
  orderLabel: 'Đơn',
  recipient: 'Người nhận',
  shipping: 'Giao hàng',
  seven: 'Nhận 7-11',
  home: 'Giao tận nhà',
  shipmentCode: 'Mã gửi ibon',
  logisticsError: 'Ghi chú logistics',
  createShipment: 'Tạo mã gửi 7-11',
  creating: 'Đang tạo...',
  createFail: 'Không tạo được',
  shipmentReady: 'Đơn #{id} mã gửi: {code}',
  loadFail: 'Tải thất bại',
  logEyebrow: 'PAYMENTS / LOGISTICS',
  logTitle: 'Thanh toán／Logistics',
  logSubtitle: 'Nhận 7-11 là tùy chọn. Để bật, hoàn tất ECPay rồi làm theo hướng dẫn. Không bật vẫn dùng giao nhà + thẻ.',
  guideCta: 'Hướng dẫn đầy đủ',
  marketTitle: 'Thị trường giao',
  marketDesc: 'Quyết định có hiện nhận tiện lợi／COD Đài Loan khi thanh toán. Ngôn ngữ site là riêng.',
  marketTw: 'Giao Đài Loan（7-11 tùy chọn）',
  marketIntl: 'Quốc tế（chỉ giao nhà＋thẻ）',
  marketTwSaved: 'Đã đặt giao Đài Loan.',
  marketIntlSaved: 'Đã đặt giao quốc tế（nhà＋thẻ）.',
  ecpayTitle: 'Đăng ký ECPay',
  ecpayDesc: 'Đăng ký／đăng nhập ECPay và xin logistics（cần cả thanh toán）. Sau duyệt, lấy MerchantID／HashKey／HashIV.',
  ecpayLogin: 'Đăng nhập bán hàng ECPay',
  ecpayHow: 'ECPay: cách xin logistics',
  ecpayHome: 'Website ECPay',
  flowTitle: 'Các bước',
  step1Title: 'Xin logistics 7-11 trên ECPay',
  step1Desc: 'Tài khoản mới bật thanh toán＋logistics; cũ thêm ở xác minh／dịch vụ. Nên C2C (UNIMARTC2C).',
  step1Link: 'Mở đăng nhập ECPay →',
  step2Title: 'Gửi thông tin nhờ ARVIX kết nối',
  step2Desc: 'Email tên cửa hàng, email, MerchantID, môi trường, nhu cầu. Đừng gửi full Hash qua email thường.',
  step2Mail: 'Email xin kết nối',
  step2Guide: 'Xem hướng dẫn',
  step3Title: 'Dùng sau khi kết nối',
  step3Desc: 'COD tạo mã sau đặt; thẻ tạo sau thanh toán. C2C in qua ibon; B2C theo ECPay.',
  warnPending: 'Trước khi kết nối chưa dùng bản đồ／mã gửi. Giao nhà＋thẻ vẫn được.',
  docsTitle: 'Tài liệu',
  docsGuide: 'Hướng dẫn đầy đủ（in／PDF）',
  docsOrders: 'Đơn & giao hàng',
  keysTitle: 'Nâng cao: khóa API',
  keysDesc: 'Nên email hỗ trợ trước. Chỉ mở khi được yêu cầu nhập khóa.',
  expand: 'Mở',
  collapse: 'Thu',
  statusReady: 'Chọn cửa＋mã gửi sẵn',
  statusConfigured: 'Đã có MerchantID',
  statusNone: 'Chưa cấu hình',
  statusLabel: 'Trạng thái',
  env: 'Môi trường',
  envStage: 'Thử stage',
  envProd: 'Production',
  subtype: 'LogisticsSubType',
  subtypeAuto: 'Tự động',
  senderName: 'Tên người gửi（ECPay）',
  senderPhone: 'SĐT người gửi（ECPay）',
  keepEmpty: 'Để trống = giữ nguyên',
  saveKeys: 'Lưu khóa',
  saving: 'Đang lưu...',
  saved: 'Đã lưu. Nhờ hỗ trợ xác nhận nếu cần.',
  saveFail: 'Lưu thất bại',
  ibonHow: 'Tại 7-11 ibon → Mua/gửi → Bưu kiện → Gửi → nhập mã → in tem',
  noShipmentYet: 'Chưa có mã gửi',
  statusPaid: 'Đã thanh toán',
  statusCod: 'COD',
  statusPending: 'Chờ thanh toán',
  statusFailed: 'Thất bại',
  statusCancelled: 'Đã hủy',
  errPaymentRequired: 'Cần thanh toán trước khi tạo mã gửi hàng',
  errEcpayNotConfigured: 'Vui lòng cấu hình ECPay trước',
  errNotCvs: 'Đơn này không phải nhận tại cửa hàng tiện lợi',
  errCvsRequired: 'Thiếu mã cửa hàng',
  errAmountLimit: 'Số tiền vượt hạn mức cửa hàng tiện lợi',
  errNoStore: 'Chưa có cửa hàng',
}

const es: MerchantOpsCopy = {
  eyebrow: 'ORDERS',
  title: 'Pedidos y envíos',
  subtitle: 'Los pedidos 7-11 muestran un código ibon. En ibon → envío → introduce el código para imprimir. ¿Aún no? Lee la guía, termina ECPay y escríbenos para integrar.',
  guideLink: 'Guía',
  backStore: 'Volver a mi tienda',
  loading: 'Cargando...',
  empty: 'Sin pedidos',
  orderLabel: 'Pedido',
  recipient: 'Destinatario',
  shipping: 'Envío',
  seven: 'Recogida 7-11',
  home: 'Entrega a domicilio',
  shipmentCode: 'Código ibon',
  logisticsError: 'Nota logística',
  createShipment: 'Crear código 7-11',
  creating: 'Creando...',
  createFail: 'No se pudo crear',
  shipmentReady: 'Pedido #{id} código: {code}',
  loadFail: 'Error al cargar',
  logEyebrow: 'PAYMENTS / LOGISTICS',
  logTitle: 'Pagos／Logística',
  logSubtitle: 'La recogida 7-11 es opcional. Para activarla, completa ECPay y sigue la guía. Sin ella siguen domicilio y tarjeta.',
  guideCta: 'Guía completa',
  marketTitle: 'Mercado de envío',
  marketDesc: 'Define si el checkout muestra recogida／COD de Taiwán. El idioma del sitio es aparte.',
  marketTw: 'Taiwán（7-11 opcional）',
  marketIntl: 'Internacional（domicilio＋tarjeta）',
  marketTwSaved: 'Configurado envío Taiwán.',
  marketIntlSaved: 'Configurado envío internacional.',
  ecpayTitle: 'Solicitud ECPay',
  ecpayDesc: 'Regístrate／entra en ECPay y solicita logística（también pagos）. Luego copia MerchantID／HashKey／HashIV.',
  ecpayLogin: 'Login vendedor ECPay',
  ecpayHow: 'ECPay: cómo solicitar logística',
  ecpayHome: 'Sitio ECPay',
  flowTitle: 'Pasos',
  step1Title: 'Solicita logística 7-11 en ECPay',
  step1Desc: 'Nuevos: pagos＋logística; existentes: añadan logística. Preferible C2C (UNIMARTC2C).',
  step1Link: 'Abrir login ECPay →',
  step2Title: 'Envía datos para integración ARVIX',
  step2Desc: 'Email con tienda, email, MerchantID, entorno y necesidades. No envíes Hash completos por correo normal.',
  step2Mail: 'Email de integración',
  step2Guide: 'Ver guía',
  step3Title: 'Listo tras integrar',
  step3Desc: 'COD crea código tras pedido; tarjeta tras pago. C2C: ibon; B2C: flujo ECPay.',
  warnPending: 'Sin integración no hay mapa／código. Domicilio y tarjeta sí.',
  docsTitle: 'Docs',
  docsGuide: 'Guía completa（imprimir／PDF）',
  docsOrders: 'Pedidos y envíos',
  keysTitle: 'Avanzado: claves',
  keysDesc: 'Mejor escribir a soporte primero. Expande solo si te lo piden.',
  expand: 'Expandir',
  collapse: 'Cerrar',
  statusReady: 'Mapa＋código listos',
  statusConfigured: 'MerchantID listo',
  statusNone: 'Sin configurar',
  statusLabel: 'Estado',
  env: 'Entorno',
  envStage: 'Prueba stage',
  envProd: 'Producción',
  subtype: 'LogisticsSubType',
  subtypeAuto: 'Auto',
  senderName: 'Nombre remitente（ECPay）',
  senderPhone: 'Teléfono remitente（ECPay）',
  keepEmpty: 'Vacío = no cambiar',
  saveKeys: 'Guardar claves',
  saving: 'Guardando...',
  saved: 'Guardado. Pide confirmación a soporte si hace falta.',
  saveFail: 'Error al guardar',
  ibonHow: 'En 7-11 ibon → Compras/envíos → Paquete → Enviar → introduce el código → imprimir',
  noShipmentYet: 'Aún no hay código de envío',
  statusPaid: 'Pagado',
  statusCod: 'Contra reembolso',
  statusPending: 'Pendiente',
  statusFailed: 'Fallido',
  statusCancelled: 'Cancelado',
  errPaymentRequired: 'El pago es necesario antes de crear el código de envío',
  errEcpayNotConfigured: 'Configura primero la logística de ECPay',
  errNotCvs: 'Este pedido no es recogida en tienda de conveniencia',
  errCvsRequired: 'Falta el ID de tienda',
  errAmountLimit: 'El importe supera el límite de tienda de conveniencia',
  errNoStore: 'Aún no hay tienda',
}

const pt: MerchantOpsCopy = {
  eyebrow: 'ORDERS',
  title: 'Pedidos e envios',
  subtitle: 'Pedidos 7-11 mostram código ibon. No ibon → envio → digite o código para imprimir. Ainda não? Leia o guia, conclua a ECPay e e-mail para integração.',
  guideLink: 'Guia',
  backStore: 'Voltar à loja',
  loading: 'Carregando...',
  empty: 'Sem pedidos',
  orderLabel: 'Pedido',
  recipient: 'Destinatário',
  shipping: 'Envio',
  seven: 'Retirada 7-11',
  home: 'Entrega em domicílio',
  shipmentCode: 'Código ibon',
  logisticsError: 'Nota logística',
  createShipment: 'Gerar código 7-11',
  creating: 'Gerando...',
  createFail: 'Falha ao gerar',
  shipmentReady: 'Pedido #{id} código: {code}',
  loadFail: 'Falha ao carregar',
  logEyebrow: 'PAYMENTS / LOGISTICS',
  logTitle: 'Pagamentos／Logística',
  logSubtitle: 'Retirada 7-11 é opcional. Para ativar, conclua ECPay e siga o guia. Sem isso, entrega e cartão continuam.',
  guideCta: 'Guia completo',
  marketTitle: 'Mercado de envio',
  marketDesc: 'Define se o checkout mostra retirada／COD de Taiwan. O idioma do site é separado.',
  marketTw: 'Taiwan（7-11 opcional）',
  marketIntl: 'Internacional（casa＋cartão）',
  marketTwSaved: 'Definido envio Taiwan.',
  marketIntlSaved: 'Definido envio internacional.',
  ecpayTitle: 'Pedido ECPay',
  ecpayDesc: 'Registre／entre na ECPay e peça logística（também pagamentos）. Depois copie MerchantID／HashKey／HashIV.',
  ecpayLogin: 'Login vendedor ECPay',
  ecpayHow: 'ECPay: como pedir logística',
  ecpayHome: 'Site ECPay',
  flowTitle: 'Passos',
  step1Title: 'Peça logística 7-11 na ECPay',
  step1Desc: 'Novos: pagamentos＋logística; existentes: adicione logística. Prefira C2C (UNIMARTC2C).',
  step1Link: 'Abrir login ECPay →',
  step2Title: 'Envie dados para integração ARVIX',
  step2Desc: 'E-mail com loja, e-mail, MerchantID, ambiente e necessidades. Não envie Hash completo por e-mail comum.',
  step2Mail: 'E-mail de integração',
  step2Guide: 'Ver guia',
  step3Title: 'Pronto após integrar',
  step3Desc: 'COD gera após pedido; cartão após pagamento. C2C: ibon; B2C: fluxo ECPay.',
  warnPending: 'Sem integração sem mapa／código. Casa e cartão ok.',
  docsTitle: 'Docs',
  docsGuide: 'Guia completo（imprimir／PDF）',
  docsOrders: 'Pedidos e envios',
  keysTitle: 'Avançado: chaves',
  keysDesc: 'Prefira e-mail ao suporte. Expanda só se pedirem.',
  expand: 'Expandir',
  collapse: 'Recolher',
  statusReady: 'Mapa＋código prontos',
  statusConfigured: 'MerchantID ok',
  statusNone: 'Não configurado',
  statusLabel: 'Status',
  env: 'Ambiente',
  envStage: 'Teste stage',
  envProd: 'Produção',
  subtype: 'LogisticsSubType',
  subtypeAuto: 'Auto',
  senderName: 'Nome remetente（ECPay）',
  senderPhone: 'Telefone remetente（ECPay）',
  keepEmpty: 'Vazio = manter',
  saveKeys: 'Salvar chaves',
  saving: 'Salvando...',
  saved: 'Salvo. Peça confirmação ao suporte se precisar.',
  saveFail: 'Falha ao salvar',
  ibonHow: 'No 7-11 ibon → Compras/envios → Encomenda → Enviar → digite o código → imprimir',
  noShipmentYet: 'Ainda sem código de envio',
  statusPaid: 'Pago',
  statusCod: 'Pagamento na entrega',
  statusPending: 'Pendente',
  statusFailed: 'Falhou',
  statusCancelled: 'Cancelado',
  errPaymentRequired: 'Pagamento necessário antes de gerar o código de envio',
  errEcpayNotConfigured: 'Configure a logística ECPay primeiro',
  errNotCvs: 'Este pedido não é retirada em loja de conveniência',
  errCvsRequired: 'Falta o ID da loja',
  errAmountLimit: 'Valor excede o limite da loja de conveniência',
  errNoStore: 'Ainda sem loja',
}

const de: MerchantOpsCopy = {
  eyebrow: 'ORDERS',
  title: 'Bestellungen & Versand',
  subtitle: '7-11-Abholungen zeigen einen ibon-Versandcode. Am ibon → Paketaufgabe → Code eingeben und Label drucken. Noch nicht aktiv? Anleitung lesen, ECPay beantragen, dann per E-Mail um Anbindung bitten.',
  guideLink: 'Anleitung',
  backStore: 'Zurück zum Shop',
  loading: 'Wird geladen...',
  empty: 'Keine Bestellungen',
  orderLabel: 'Bestellung',
  recipient: 'Empfänger',
  shipping: 'Versand',
  seven: '7-11 Abholung',
  home: 'Lieferung nach Hause',
  shipmentCode: 'ibon-Versandcode',
  logisticsError: 'Logistik-Hinweis',
  createShipment: '7-11-Code erzeugen',
  creating: 'Wird erzeugt...',
  createFail: 'Erzeugen fehlgeschlagen',
  shipmentReady: 'Bestellung #{id} Code: {code}',
  loadFail: 'Laden fehlgeschlagen',
  logEyebrow: 'PAYMENTS / LOGISTICS',
  logTitle: 'Zahlungen／Logistik',
  logSubtitle: '7-11-Abholung ist optional. Zum Aktivieren ECPay abschließen und der Anleitung folgen. Ohne sie bleiben Lieferung und Karte nutzbar.',
  guideCta: 'Volle Anleitung',
  marketTitle: 'Versandmarkt',
  marketDesc: 'Steuert, ob Taiwan-Filialabholung／Nachnahme im Checkout erscheinen. Die Site-Sprache ist getrennt.',
  marketTw: 'Taiwan（7-11 optional）',
  marketIntl: 'International（nur Haus＋Karte）',
  marketTwSaved: 'Taiwan-Versand gesetzt.',
  marketIntlSaved: 'Internationaler Versand gesetzt.',
  ecpayTitle: 'ECPay-Antrag',
  ecpayDesc: 'Bei ECPay registrieren／anmelden und Logistik beantragen（auch Zahlungen）. Danach MerchantID／HashKey／HashIV kopieren.',
  ecpayLogin: 'ECPay-Verkäufer-Login',
  ecpayHow: 'ECPay: Logistik beantragen',
  ecpayHome: 'ECPay-Website',
  flowTitle: 'Schritte',
  step1Title: '7-11-Logistik bei ECPay',
  step1Desc: 'Neu: Zahlungen＋Logistik; bestehend: Logistik hinzufügen. C2C (UNIMARTC2C) empfohlen.',
  step1Link: 'ECPay-Login öffnen →',
  step2Title: 'Daten an ARVIX zur Anbindung',
  step2Desc: 'E-Mail mit Shopname, E-Mail, MerchantID, Umgebung und Bedarf. Keine vollen Hash-Geheimnisse per Normal-Mail.',
  step2Mail: 'Anbindungs-E-Mail',
  step2Guide: 'Anleitung ansehen',
  step3Title: 'Nach Anbindung nutzbar',
  step3Desc: 'Nachnahme-Code nach Bestellung; Karte nach Zahlung. C2C: ibon; B2C: ECPay-Bulk.',
  warnPending: 'Ohne Anbindung kein Karten-Pickup／Code. Haus＋Karte ok.',
  docsTitle: 'Docs',
  docsGuide: 'Volle Anleitung（Druck／PDF）',
  docsOrders: 'Bestellungen & Versand',
  keysTitle: 'Erweitert: API-Schlüssel',
  keysDesc: 'Zuerst Support mailen. Nur aufklappen, wenn Sie Schlüssel selbst eintragen sollen.',
  expand: 'Aufklappen',
  collapse: 'Zuklappen',
  statusReady: 'Karte＋Code bereit',
  statusConfigured: 'MerchantID gesetzt',
  statusNone: 'Nicht konfiguriert',
  statusLabel: 'Status',
  env: 'Umgebung',
  envStage: 'Test stage',
  envProd: 'Produktion',
  subtype: 'LogisticsSubType',
  subtypeAuto: 'Auto',
  senderName: 'Absendername（ECPay）',
  senderPhone: 'Absendertelefon（ECPay）',
  keepEmpty: 'Leer = unverändert',
  saveKeys: 'Schlüssel speichern',
  saving: 'Speichert...',
  saved: 'Gespeichert. Support bei Bedarf um Bestätigung bitten.',
  saveFail: 'Speichern fehlgeschlagen',
  ibonHow: 'Bei 7-11 ibon → Einkauf/Versand → Paket → Versenden → Code eingeben → drucken',
  noShipmentYet: 'Noch kein Versandcode',
  statusPaid: 'Bezahlt',
  statusCod: 'Nachnahme',
  statusPending: 'Zahlung ausstehend',
  statusFailed: 'Fehlgeschlagen',
  statusCancelled: 'Storniert',
  errPaymentRequired: 'Zahlung erforderlich, bevor ein Versandcode erstellt wird',
  errEcpayNotConfigured: 'Bitte zuerst ECPay-Logistik konfigurieren',
  errNotCvs: 'Keine Convenience-Store-Abholung',
  errCvsRequired: 'Filial-ID fehlt',
  errAmountLimit: 'Betrag überschreitet Convenience-Store-Limit',
  errNoStore: 'Noch kein Shop',
}

const fr: MerchantOpsCopy = {
  eyebrow: 'ORDERS',
  title: 'Commandes et envois',
  subtitle: 'Les commandes 7-11 affichent un code ibon. Sur ibon → envoi → saisissez le code pour imprimer. Pas encore activé ? Lisez le guide, terminez ECPay, puis écrivez-nous pour l’intégration.',
  guideLink: 'Guide',
  backStore: 'Retour à ma boutique',
  loading: 'Chargement...',
  empty: 'Aucune commande',
  orderLabel: 'Commande',
  recipient: 'Destinataire',
  shipping: 'Livraison',
  seven: 'Retrait 7-11',
  home: 'Livraison à domicile',
  shipmentCode: 'Code ibon',
  logisticsError: 'Note logistique',
  createShipment: 'Créer le code 7-11',
  creating: 'Création...',
  createFail: 'Échec de création',
  shipmentReady: 'Commande #{id} code : {code}',
  loadFail: 'Échec du chargement',
  logEyebrow: 'PAYMENTS / LOGISTICS',
  logTitle: 'Paiements／Logistique',
  logSubtitle: 'Le retrait 7-11 est optionnel. Pour l’activer, terminez ECPay puis suivez le guide. Sans cela, domicile et carte restent disponibles.',
  guideCta: 'Guide complet',
  marketTitle: 'Marché d’expédition',
  marketDesc: 'Détermine si le checkout affiche le retrait／COD Taïwan. La langue du site est séparée.',
  marketTw: 'Taïwan（7-11 optionnel）',
  marketIntl: 'International（domicile＋carte）',
  marketTwSaved: 'Expédition Taïwan définie.',
  marketIntlSaved: 'Expédition internationale définie.',
  ecpayTitle: 'Demande ECPay',
  ecpayDesc: 'Inscrivez／connectez-vous sur ECPay et demandez la logistique（paiements aussi）. Puis copiez MerchantID／HashKey／HashIV.',
  ecpayLogin: 'Login vendeur ECPay',
  ecpayHow: 'ECPay : demander la logistique',
  ecpayHome: 'Site ECPay',
  flowTitle: 'Étapes',
  step1Title: 'Demander la logistique 7-11 sur ECPay',
  step1Desc: 'Nouveaux : paiements＋logistique ; existants : ajoutez la logistique. Préférez C2C (UNIMARTC2C).',
  step1Link: 'Ouvrir le login ECPay →',
  step2Title: 'Envoyer les infos pour intégration ARVIX',
  step2Desc: 'E-mail avec boutique, e-mail, MerchantID, environnement et besoins. N’envoyez pas les Hash complets par e-mail ordinaire.',
  step2Mail: 'E-mail d’intégration',
  step2Guide: 'Voir le guide',
  step3Title: 'Prêt après intégration',
  step3Desc: 'COD crée le code après commande ; carte après paiement. C2C : ibon ; B2C : flux ECPay.',
  warnPending: 'Sans intégration, pas de carte／code. Domicile et carte OK.',
  docsTitle: 'Docs',
  docsGuide: 'Guide complet（imprimer／PDF）',
  docsOrders: 'Commandes et envois',
  keysTitle: 'Avancé : clés API',
  keysDesc: 'Préférez écrire au support. N’ouvrez que si on vous demande de saisir les clés.',
  expand: 'Ouvrir',
  collapse: 'Réduire',
  statusReady: 'Carte＋code prêts',
  statusConfigured: 'MerchantID défini',
  statusNone: 'Non configuré',
  statusLabel: 'Statut',
  env: 'Environnement',
  envStage: 'Test stage',
  envProd: 'Production',
  subtype: 'LogisticsSubType',
  subtypeAuto: 'Auto',
  senderName: 'Nom expéditeur（ECPay）',
  senderPhone: 'Téléphone expéditeur（ECPay）',
  keepEmpty: 'Vide = inchangé',
  saveKeys: 'Enregistrer les clés',
  saving: 'Enregistrement...',
  saved: 'Enregistré. Demandez confirmation au support si besoin.',
  saveFail: 'Échec de l’enregistrement',
  ibonHow: 'Sur 7-11 ibon → Achats/envoi → Colis → Expédier → saisir le code → imprimer',
  noShipmentYet: 'Pas encore de code d’expédition',
  statusPaid: 'Payé',
  statusCod: 'Paiement à la livraison',
  statusPending: 'En attente',
  statusFailed: 'Échoué',
  statusCancelled: 'Annulé',
  errPaymentRequired: 'Paiement requis avant de créer le code d’expédition',
  errEcpayNotConfigured: 'Configurez d’abord la logistique ECPay',
  errNotCvs: 'Cette commande n’est pas un retrait en convenience store',
  errCvsRequired: 'Identifiant magasin manquant',
  errAmountLimit: 'Montant au-delà de la limite convenience store',
  errNoStore: 'Pas encore de boutique',
}

export const merchantOpsCopyByLocale: Record<Locale, MerchantOpsCopy> = {
  'zh-TW': zhTW,
  'zh-CN': zhCN,
  en, ko, ja, vi, es, pt, de, fr,
}

export function getMerchantOpsCopy(locale: Locale): MerchantOpsCopy {
  return merchantOpsCopyByLocale[locale] || merchantOpsCopyByLocale.en
}
